<?php

use Illuminate\Database\Seeder;

class BomComponentTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('bom_component')->delete();
        
        \DB::table('bom_component')->insert(array (
            0 => 
            array (
                'id' => 1,
                'bom_id' => 3,
                'product_feature_id' => 151,
                'qty' => 1.32,
                'consumption' => 1.32,
                'allowance' => 0.0,
                'unit_price' => 51000.0,
                'created_at' => NULL,
                'updated_at' => '2022-09-27 07:25:50',
            ),
            1 => 
            array (
                'id' => 2,
                'bom_id' => 3,
                'product_feature_id' => 152,
                'qty' => 0.2302,
                'consumption' => 0.2132,
                'allowance' => 0.0107,
                'unit_price' => 9500.0,
                'created_at' => NULL,
                'updated_at' => '2022-09-23 07:09:17',
            ),
            2 => 
            array (
                'id' => 3,
                'bom_id' => 3,
                'product_feature_id' => 153,
                'qty' => 0.0525,
                'consumption' => 0.05,
                'allowance' => 0.0025,
                'unit_price' => 14000.0,
                'created_at' => NULL,
                'updated_at' => '2022-09-23 06:57:56',
            ),
            3 => 
            array (
                'id' => 4,
                'bom_id' => 3,
                'product_feature_id' => 154,
                'qty' => 6.3,
                'consumption' => 6.0,
                'allowance' => 0.3,
                'unit_price' => 300.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'bom_id' => 3,
                'product_feature_id' => 155,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 800.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'bom_id' => 3,
                'product_feature_id' => 156,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 250.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'bom_id' => 3,
                'product_feature_id' => 158,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 600.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'bom_id' => 3,
                'product_feature_id' => 159,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 1800.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'bom_id' => 3,
                'product_feature_id' => 160,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 200.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'bom_id' => 3,
                'product_feature_id' => 161,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 700.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'bom_id' => 3,
                'product_feature_id' => 162,
                'qty' => 0.042,
                'consumption' => 0.04,
                'allowance' => 0.002,
                'unit_price' => 25000.0,
                'created_at' => NULL,
                'updated_at' => '2022-09-23 07:26:59',
            ),
            11 => 
            array (
                'id' => 12,
                'bom_id' => 3,
                'product_feature_id' => 163,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 500.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'bom_id' => 2,
                'product_feature_id' => 165,
                'qty' => 1.35,
                'consumption' => 1.35,
                'allowance' => 0.0,
                'unit_price' => 44800.0,
                'created_at' => '2022-09-27 00:20:04',
                'updated_at' => '2022-09-27 01:15:38',
            ),
            13 => 
            array (
                'id' => 14,
                'bom_id' => 2,
                'product_feature_id' => 152,
                'qty' => 0.224,
                'consumption' => 0.2132,
                'allowance' => 0.011,
                'unit_price' => 9500.0,
                'created_at' => '2022-09-27 01:04:05',
                'updated_at' => '2022-09-27 07:32:16',
            ),
            14 => 
            array (
                'id' => 15,
                'bom_id' => 2,
                'product_feature_id' => 153,
                'qty' => 0.0525,
                'consumption' => 0.05,
                'allowance' => 0.0025,
                'unit_price' => 14000.0,
                'created_at' => '2022-09-27 01:04:05',
                'updated_at' => '2022-09-27 01:16:08',
            ),
            15 => 
            array (
                'id' => 16,
                'bom_id' => 2,
                'product_feature_id' => 154,
                'qty' => 6.3,
                'consumption' => 6.0,
                'allowance' => 0.3,
                'unit_price' => 300.0,
                'created_at' => '2022-09-27 01:04:05',
                'updated_at' => '2022-09-27 01:16:13',
            ),
            16 => 
            array (
                'id' => 17,
                'bom_id' => 2,
                'product_feature_id' => 155,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 800.0,
                'created_at' => '2022-09-27 01:04:05',
                'updated_at' => '2022-09-27 01:16:20',
            ),
            17 => 
            array (
                'id' => 18,
                'bom_id' => 2,
                'product_feature_id' => 156,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 250.0,
                'created_at' => '2022-09-27 01:04:05',
                'updated_at' => '2022-09-27 01:16:23',
            ),
            18 => 
            array (
                'id' => 19,
                'bom_id' => 2,
                'product_feature_id' => 158,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 600.0,
                'created_at' => '2022-09-27 01:04:05',
                'updated_at' => '2022-09-27 01:16:27',
            ),
            19 => 
            array (
                'id' => 20,
                'bom_id' => 2,
                'product_feature_id' => 159,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 1800.0,
                'created_at' => '2022-09-27 01:04:05',
                'updated_at' => '2022-09-27 01:16:30',
            ),
            20 => 
            array (
                'id' => 21,
                'bom_id' => 2,
                'product_feature_id' => 160,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 200.0,
                'created_at' => '2022-09-27 01:04:05',
                'updated_at' => '2022-09-27 01:16:33',
            ),
            21 => 
            array (
                'id' => 22,
                'bom_id' => 2,
                'product_feature_id' => 161,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 700.0,
                'created_at' => '2022-09-27 01:04:05',
                'updated_at' => '2022-09-27 01:16:37',
            ),
            22 => 
            array (
                'id' => 23,
                'bom_id' => 2,
                'product_feature_id' => 162,
                'qty' => 0.042,
                'consumption' => 0.04,
                'allowance' => 0.002,
                'unit_price' => 25000.0,
                'created_at' => '2022-09-27 01:04:05',
                'updated_at' => '2022-09-27 01:16:45',
            ),
            23 => 
            array (
                'id' => 24,
                'bom_id' => 2,
                'product_feature_id' => 163,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 500.0,
                'created_at' => '2022-09-27 01:04:05',
                'updated_at' => '2022-09-27 01:16:48',
            ),
            24 => 
            array (
                'id' => 25,
                'bom_id' => 4,
                'product_feature_id' => 152,
                'qty' => 0.1907,
                'consumption' => 0.1817,
                'allowance' => 0.00954,
                'unit_price' => 9500.0,
                'created_at' => '2022-10-04 04:30:05',
                'updated_at' => '2022-10-14 07:35:22',
            ),
            25 => 
            array (
                'id' => 28,
                'bom_id' => 8,
                'product_feature_id' => 187,
                'qty' => 0.03,
                'consumption' => 0.03,
                'allowance' => 0.0,
                'unit_price' => 11700.0,
                'created_at' => '2022-10-05 02:26:40',
                'updated_at' => '2022-10-05 02:30:19',
            ),
            26 => 
            array (
                'id' => 29,
                'bom_id' => 8,
                'product_feature_id' => 189,
                'qty' => 0.02,
                'consumption' => 0.02,
                'allowance' => 0.0,
                'unit_price' => 11700.0,
                'created_at' => '2022-10-05 02:26:40',
                'updated_at' => '2022-10-05 02:30:23',
            ),
            27 => 
            array (
                'id' => 30,
                'bom_id' => 8,
                'product_feature_id' => 161,
                'qty' => 1.0,
                'consumption' => 6.0,
                'allowance' => 0.0,
                'unit_price' => 735.0,
                'created_at' => '2022-10-05 02:28:10',
                'updated_at' => '2022-10-05 02:30:40',
            ),
            28 => 
            array (
                'id' => 31,
                'bom_id' => 9,
                'product_feature_id' => 153,
                'qty' => 0.04,
                'consumption' => 0.03,
                'allowance' => 0.01,
                'unit_price' => 0.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            29 => 
            array (
                'id' => 32,
                'bom_id' => 10,
                'product_feature_id' => 153,
                'qty' => 0.04,
                'consumption' => 0.03,
                'allowance' => 0.01,
                'unit_price' => 0.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            30 => 
            array (
                'id' => 33,
                'bom_id' => 11,
                'product_feature_id' => 153,
                'qty' => 0.04,
                'consumption' => 0.03,
                'allowance' => 0.01,
                'unit_price' => 0.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            31 => 
            array (
                'id' => 35,
                'bom_id' => 12,
                'product_feature_id' => 321,
                'qty' => 0.03,
                'consumption' => 0.03,
                'allowance' => 0.0,
                'unit_price' => 28000.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            32 => 
            array (
                'id' => 37,
                'bom_id' => 13,
                'product_feature_id' => 321,
                'qty' => 0.03,
                'consumption' => 0.03,
                'allowance' => 0.0,
                'unit_price' => 11800.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            33 => 
            array (
                'id' => 38,
                'bom_id' => 12,
                'product_feature_id' => 323,
                'qty' => 0.05,
                'consumption' => 0.05,
                'allowance' => 0.0,
                'unit_price' => 28000.0,
                'created_at' => '2022-10-13 04:20:25',
                'updated_at' => '2022-10-13 04:47:40',
            ),
            34 => 
            array (
                'id' => 39,
                'bom_id' => 13,
                'product_feature_id' => 323,
                'qty' => 0.05,
                'consumption' => 0.05,
                'allowance' => 0.0,
                'unit_price' => 11800.0,
                'created_at' => '2022-10-13 04:22:58',
                'updated_at' => '2022-10-13 04:47:29',
            ),
            35 => 
            array (
                'id' => 40,
                'bom_id' => 4,
                'product_feature_id' => 119,
                'qty' => 0.0525,
                'consumption' => 0.05,
                'allowance' => 0.002625,
                'unit_price' => 15000.0,
                'created_at' => '2022-10-13 06:11:25',
                'updated_at' => '2022-10-14 07:35:47',
            ),
            36 => 
            array (
                'id' => 41,
                'bom_id' => 4,
                'product_feature_id' => 120,
                'qty' => 11.55,
                'consumption' => 11.0,
                'allowance' => 0.5775,
                'unit_price' => 220.0,
                'created_at' => '2022-10-13 06:11:25',
                'updated_at' => '2022-10-14 07:36:01',
            ),
            37 => 
            array (
                'id' => 42,
                'bom_id' => 4,
                'product_feature_id' => 155,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.0525,
                'unit_price' => 620.0,
                'created_at' => '2022-10-13 06:11:25',
                'updated_at' => '2022-10-14 07:37:42',
            ),
            38 => 
            array (
                'id' => 43,
                'bom_id' => 4,
                'product_feature_id' => 156,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.0525,
                'unit_price' => 100.0,
                'created_at' => '2022-10-13 06:11:25',
                'updated_at' => '2022-10-14 07:37:51',
            ),
            39 => 
            array (
                'id' => 44,
                'bom_id' => 4,
                'product_feature_id' => 158,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.0525,
                'unit_price' => 100.0,
                'created_at' => '2022-10-13 06:11:25',
                'updated_at' => '2022-10-14 07:37:56',
            ),
            40 => 
            array (
                'id' => 45,
                'bom_id' => 4,
                'product_feature_id' => 159,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.0525,
                'unit_price' => 1150.0,
                'created_at' => '2022-10-13 06:11:25',
                'updated_at' => '2022-10-14 07:38:02',
            ),
            41 => 
            array (
                'id' => 46,
                'bom_id' => 4,
                'product_feature_id' => 160,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.0525,
                'unit_price' => 220.0,
                'created_at' => '2022-10-13 06:11:25',
                'updated_at' => '2022-10-14 07:38:07',
            ),
            42 => 
            array (
                'id' => 47,
                'bom_id' => 4,
                'product_feature_id' => 161,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.0525,
                'unit_price' => 670.0,
                'created_at' => '2022-10-13 06:11:25',
                'updated_at' => '2022-10-14 07:38:11',
            ),
            43 => 
            array (
                'id' => 48,
                'bom_id' => 4,
                'product_feature_id' => 162,
                'qty' => 0.042,
                'consumption' => 0.04,
                'allowance' => 0.0021,
                'unit_price' => 25000.0,
                'created_at' => '2022-10-13 06:11:25',
                'updated_at' => '2022-10-14 07:37:05',
            ),
            44 => 
            array (
                'id' => 49,
                'bom_id' => 4,
                'product_feature_id' => 163,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.0525,
                'unit_price' => 500.0,
                'created_at' => '2022-10-13 06:11:25',
                'updated_at' => '2022-10-14 07:37:29',
            ),
            45 => 
            array (
                'id' => 50,
                'bom_id' => 14,
                'product_feature_id' => 322,
                'qty' => 0.042,
                'consumption' => 0.04,
                'allowance' => 0.002,
                'unit_price' => 28000.0,
                'created_at' => '2022-10-14 00:29:24',
                'updated_at' => '2022-10-14 00:29:59',
            ),
            46 => 
            array (
                'id' => 53,
                'bom_id' => 4,
                'product_feature_id' => 117,
                'qty' => 1.31,
                'consumption' => 1.3,
                'allowance' => 0.0,
                'unit_price' => 29279.0,
                'created_at' => '2022-10-14 00:49:38',
                'updated_at' => '2022-10-29 02:49:13',
            ),
            47 => 
            array (
                'id' => 54,
                'bom_id' => 20,
                'product_feature_id' => 323,
                'qty' => 0.052500000000000005,
                'consumption' => 0.05,
                'allowance' => 0.0025,
                'unit_price' => 28000.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            48 => 
            array (
                'id' => 55,
                'bom_id' => 20,
                'product_feature_id' => 322,
                'qty' => 0.042,
                'consumption' => 0.04,
                'allowance' => 0.002,
                'unit_price' => 28000.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            49 => 
            array (
                'id' => 58,
                'bom_id' => 20,
                'product_feature_id' => 373,
                'qty' => 0.0315,
                'consumption' => 0.03,
                'allowance' => 0.0015,
                'unit_price' => 28000.0,
                'created_at' => '2022-10-19 06:37:38',
                'updated_at' => '2022-10-19 06:39:16',
            ),
            50 => 
            array (
                'id' => 59,
                'bom_id' => 21,
                'product_feature_id' => 322,
                'qty' => 0.042,
                'consumption' => 0.04,
                'allowance' => 0.002,
                'unit_price' => 28000.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            51 => 
            array (
                'id' => 60,
                'bom_id' => 21,
                'product_feature_id' => 323,
                'qty' => 0.052500000000000005,
                'consumption' => 0.05,
                'allowance' => 0.0025,
                'unit_price' => 28000.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            52 => 
            array (
                'id' => 61,
                'bom_id' => 21,
                'product_feature_id' => 321,
                'qty' => 0.0315,
                'consumption' => 0.03,
                'allowance' => 0.0015,
                'unit_price' => 28000.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            53 => 
            array (
                'id' => 62,
                'bom_id' => 21,
                'product_feature_id' => 152,
                'qty' => 0.3,
                'consumption' => 0.3,
                'allowance' => 0.0,
                'unit_price' => 28000.0,
                'created_at' => '2022-10-19 06:49:03',
                'updated_at' => '2022-10-19 06:49:26',
            ),
            54 => 
            array (
                'id' => 64,
                'bom_id' => 14,
                'product_feature_id' => 373,
                'qty' => 0.043,
                'consumption' => 0.04,
                'allowance' => 0.003,
                'unit_price' => 28000.0,
                'created_at' => '2022-10-23 03:52:38',
                'updated_at' => '2022-10-23 03:53:12',
            ),
            55 => 
            array (
                'id' => 65,
                'bom_id' => 14,
                'product_feature_id' => 323,
                'qty' => 0.06,
                'consumption' => 0.05,
                'allowance' => 0.01,
                'unit_price' => 28000.0,
                'created_at' => '2022-10-23 03:53:55',
                'updated_at' => '2022-10-23 03:54:21',
            ),
        ));
        
        
    }
}