<?php

use Illuminate\Database\Seeder;

class BomComponentTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('bom_component')->delete();
        
        \DB::table('bom_component')->insert(array (
            0 => 
            array (
                'id' => 1,
                'bom_id' => 3,
                'product_feature_id' => 151,
                'qty' => 1.32,
                'consumption' => 1.32,
                'allowance' => 0.0,
                'unit_price' => 51000.0,
                'created_at' => NULL,
                'updated_at' => '2022-09-27 07:25:50',
            ),
            1 => 
            array (
                'id' => 2,
                'bom_id' => 3,
                'product_feature_id' => 152,
                'qty' => 0.2302,
                'consumption' => 0.2132,
                'allowance' => 0.0107,
                'unit_price' => 9500.0,
                'created_at' => NULL,
                'updated_at' => '2022-09-23 07:09:17',
            ),
            2 => 
            array (
                'id' => 3,
                'bom_id' => 3,
                'product_feature_id' => 153,
                'qty' => 0.0525,
                'consumption' => 0.05,
                'allowance' => 0.0025,
                'unit_price' => 14000.0,
                'created_at' => NULL,
                'updated_at' => '2022-09-23 06:57:56',
            ),
            3 => 
            array (
                'id' => 4,
                'bom_id' => 3,
                'product_feature_id' => 154,
                'qty' => 6.3,
                'consumption' => 6.0,
                'allowance' => 0.3,
                'unit_price' => 300.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'bom_id' => 3,
                'product_feature_id' => 155,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 800.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'bom_id' => 3,
                'product_feature_id' => 156,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 250.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'bom_id' => 3,
                'product_feature_id' => 158,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 600.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'bom_id' => 3,
                'product_feature_id' => 159,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 1800.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'bom_id' => 3,
                'product_feature_id' => 160,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 200.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'bom_id' => 3,
                'product_feature_id' => 161,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 700.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'bom_id' => 3,
                'product_feature_id' => 162,
                'qty' => 0.042,
                'consumption' => 0.04,
                'allowance' => 0.002,
                'unit_price' => 25000.0,
                'created_at' => NULL,
                'updated_at' => '2022-09-23 07:26:59',
            ),
            11 => 
            array (
                'id' => 12,
                'bom_id' => 3,
                'product_feature_id' => 163,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 500.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'bom_id' => 2,
                'product_feature_id' => 165,
                'qty' => 1.35,
                'consumption' => 1.35,
                'allowance' => 0.0,
                'unit_price' => 44800.0,
                'created_at' => '2022-09-27 00:20:04',
                'updated_at' => '2022-09-27 01:15:38',
            ),
            13 => 
            array (
                'id' => 14,
                'bom_id' => 2,
                'product_feature_id' => 152,
                'qty' => 0.224,
                'consumption' => 0.2132,
                'allowance' => 0.011,
                'unit_price' => 9500.0,
                'created_at' => '2022-09-27 01:04:05',
                'updated_at' => '2022-09-27 07:32:16',
            ),
            14 => 
            array (
                'id' => 15,
                'bom_id' => 2,
                'product_feature_id' => 153,
                'qty' => 0.0525,
                'consumption' => 0.05,
                'allowance' => 0.0025,
                'unit_price' => 14000.0,
                'created_at' => '2022-09-27 01:04:05',
                'updated_at' => '2022-09-27 01:16:08',
            ),
            15 => 
            array (
                'id' => 16,
                'bom_id' => 2,
                'product_feature_id' => 154,
                'qty' => 6.3,
                'consumption' => 6.0,
                'allowance' => 0.3,
                'unit_price' => 300.0,
                'created_at' => '2022-09-27 01:04:05',
                'updated_at' => '2022-09-27 01:16:13',
            ),
            16 => 
            array (
                'id' => 17,
                'bom_id' => 2,
                'product_feature_id' => 155,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 800.0,
                'created_at' => '2022-09-27 01:04:05',
                'updated_at' => '2022-09-27 01:16:20',
            ),
            17 => 
            array (
                'id' => 18,
                'bom_id' => 2,
                'product_feature_id' => 156,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 250.0,
                'created_at' => '2022-09-27 01:04:05',
                'updated_at' => '2022-09-27 01:16:23',
            ),
            18 => 
            array (
                'id' => 19,
                'bom_id' => 2,
                'product_feature_id' => 158,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 600.0,
                'created_at' => '2022-09-27 01:04:05',
                'updated_at' => '2022-09-27 01:16:27',
            ),
            19 => 
            array (
                'id' => 20,
                'bom_id' => 2,
                'product_feature_id' => 159,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 1800.0,
                'created_at' => '2022-09-27 01:04:05',
                'updated_at' => '2022-09-27 01:16:30',
            ),
            20 => 
            array (
                'id' => 21,
                'bom_id' => 2,
                'product_feature_id' => 160,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 200.0,
                'created_at' => '2022-09-27 01:04:05',
                'updated_at' => '2022-09-27 01:16:33',
            ),
            21 => 
            array (
                'id' => 22,
                'bom_id' => 2,
                'product_feature_id' => 161,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 700.0,
                'created_at' => '2022-09-27 01:04:05',
                'updated_at' => '2022-09-27 01:16:37',
            ),
            22 => 
            array (
                'id' => 23,
                'bom_id' => 2,
                'product_feature_id' => 162,
                'qty' => 0.042,
                'consumption' => 0.04,
                'allowance' => 0.002,
                'unit_price' => 25000.0,
                'created_at' => '2022-09-27 01:04:05',
                'updated_at' => '2022-09-27 01:16:45',
            ),
            23 => 
            array (
                'id' => 24,
                'bom_id' => 2,
                'product_feature_id' => 163,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 500.0,
                'created_at' => '2022-09-27 01:04:05',
                'updated_at' => '2022-09-27 01:16:48',
            ),
            24 => 
            array (
                'id' => 25,
                'bom_id' => 4,
                'product_feature_id' => 152,
                'qty' => 5.1817,
                'consumption' => 0.1817,
                'allowance' => 5.0,
                'unit_price' => 9500.0,
                'created_at' => '2022-10-04 04:30:05',
                'updated_at' => '2022-11-16 13:29:38',
            ),
            25 => 
            array (
                'id' => 28,
                'bom_id' => 8,
                'product_feature_id' => 187,
                'qty' => 0.03,
                'consumption' => 0.03,
                'allowance' => 0.0,
                'unit_price' => 11700.0,
                'created_at' => '2022-10-05 02:26:40',
                'updated_at' => '2022-10-05 02:30:19',
            ),
            26 => 
            array (
                'id' => 29,
                'bom_id' => 8,
                'product_feature_id' => 189,
                'qty' => 0.02,
                'consumption' => 0.02,
                'allowance' => 0.0,
                'unit_price' => 11700.0,
                'created_at' => '2022-10-05 02:26:40',
                'updated_at' => '2022-10-05 02:30:23',
            ),
            27 => 
            array (
                'id' => 30,
                'bom_id' => 8,
                'product_feature_id' => 161,
                'qty' => 1.0,
                'consumption' => 6.0,
                'allowance' => 0.0,
                'unit_price' => 735.0,
                'created_at' => '2022-10-05 02:28:10',
                'updated_at' => '2022-10-05 02:30:40',
            ),
            28 => 
            array (
                'id' => 31,
                'bom_id' => 9,
                'product_feature_id' => 153,
                'qty' => 0.04,
                'consumption' => 0.03,
                'allowance' => 0.01,
                'unit_price' => 0.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            29 => 
            array (
                'id' => 32,
                'bom_id' => 10,
                'product_feature_id' => 153,
                'qty' => 0.04,
                'consumption' => 0.03,
                'allowance' => 0.01,
                'unit_price' => 0.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            30 => 
            array (
                'id' => 33,
                'bom_id' => 11,
                'product_feature_id' => 153,
                'qty' => 0.04,
                'consumption' => 0.03,
                'allowance' => 0.01,
                'unit_price' => 0.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            31 => 
            array (
                'id' => 35,
                'bom_id' => 12,
                'product_feature_id' => 321,
                'qty' => 0.03,
                'consumption' => 0.03,
                'allowance' => 0.0,
                'unit_price' => 28000.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            32 => 
            array (
                'id' => 37,
                'bom_id' => 13,
                'product_feature_id' => 321,
                'qty' => 0.03,
                'consumption' => 0.03,
                'allowance' => 0.0,
                'unit_price' => 11800.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            33 => 
            array (
                'id' => 38,
                'bom_id' => 12,
                'product_feature_id' => 323,
                'qty' => 0.05,
                'consumption' => 0.05,
                'allowance' => 0.0,
                'unit_price' => 28000.0,
                'created_at' => '2022-10-13 04:20:25',
                'updated_at' => '2022-10-13 04:47:40',
            ),
            34 => 
            array (
                'id' => 39,
                'bom_id' => 13,
                'product_feature_id' => 323,
                'qty' => 0.05,
                'consumption' => 0.05,
                'allowance' => 0.0,
                'unit_price' => 11800.0,
                'created_at' => '2022-10-13 04:22:58',
                'updated_at' => '2022-10-13 04:47:29',
            ),
            35 => 
            array (
                'id' => 40,
                'bom_id' => 4,
                'product_feature_id' => 119,
                'qty' => 5.17,
                'consumption' => 0.05,
                'allowance' => 5.0,
                'unit_price' => 15000.0,
                'created_at' => '2022-10-13 06:11:25',
                'updated_at' => '2022-11-16 14:27:43',
            ),
            36 => 
            array (
                'id' => 42,
                'bom_id' => 4,
                'product_feature_id' => 155,
                'qty' => 1.0525,
                'consumption' => 1.0,
                'allowance' => 0.0525,
                'unit_price' => 620.0,
                'created_at' => '2022-10-13 06:11:25',
                'updated_at' => '2022-11-16 14:00:08',
            ),
            37 => 
            array (
                'id' => 43,
                'bom_id' => 4,
                'product_feature_id' => 156,
                'qty' => 1.0525,
                'consumption' => 1.0,
                'allowance' => 0.0525,
                'unit_price' => 100.0,
                'created_at' => '2022-10-13 06:11:25',
                'updated_at' => '2022-11-16 14:00:08',
            ),
            38 => 
            array (
                'id' => 44,
                'bom_id' => 4,
                'product_feature_id' => 158,
                'qty' => 1.0525,
                'consumption' => 1.0,
                'allowance' => 0.0525,
                'unit_price' => 100.0,
                'created_at' => '2022-10-13 06:11:25',
                'updated_at' => '2022-11-16 14:00:08',
            ),
            39 => 
            array (
                'id' => 45,
                'bom_id' => 4,
                'product_feature_id' => 159,
                'qty' => 1.0525,
                'consumption' => 1.0,
                'allowance' => 0.0525,
                'unit_price' => 1150.0,
                'created_at' => '2022-10-13 06:11:25',
                'updated_at' => '2022-11-16 14:00:08',
            ),
            40 => 
            array (
                'id' => 46,
                'bom_id' => 4,
                'product_feature_id' => 160,
                'qty' => 1.0525,
                'consumption' => 1.0,
                'allowance' => 0.0525,
                'unit_price' => 220.0,
                'created_at' => '2022-10-13 06:11:25',
                'updated_at' => '2022-11-16 14:00:09',
            ),
            41 => 
            array (
                'id' => 47,
                'bom_id' => 4,
                'product_feature_id' => 161,
                'qty' => 1.0525,
                'consumption' => 1.0,
                'allowance' => 0.0525,
                'unit_price' => 670.0,
                'created_at' => '2022-10-13 06:11:25',
                'updated_at' => '2022-11-16 14:00:09',
            ),
            42 => 
            array (
                'id' => 48,
                'bom_id' => 4,
                'product_feature_id' => 162,
                'qty' => 0.0421,
                'consumption' => 0.04,
                'allowance' => 0.0021,
                'unit_price' => 25000.0,
                'created_at' => '2022-10-13 06:11:25',
                'updated_at' => '2022-11-16 14:00:11',
            ),
            43 => 
            array (
                'id' => 49,
                'bom_id' => 4,
                'product_feature_id' => 163,
                'qty' => 1.0525,
                'consumption' => 1.0,
                'allowance' => 0.0525,
                'unit_price' => 500.0,
                'created_at' => '2022-10-13 06:11:25',
                'updated_at' => '2022-11-16 14:00:11',
            ),
            44 => 
            array (
                'id' => 50,
                'bom_id' => 14,
                'product_feature_id' => 322,
                'qty' => 0.042,
                'consumption' => 0.04,
                'allowance' => 0.002,
                'unit_price' => 28000.0,
                'created_at' => '2022-10-14 00:29:24',
                'updated_at' => '2022-10-14 00:29:59',
            ),
            45 => 
            array (
                'id' => 53,
                'bom_id' => 4,
                'product_feature_id' => 117,
                'qty' => 1.31,
                'consumption' => 1.3,
                'allowance' => 0.0,
                'unit_price' => 29279.0,
                'created_at' => '2022-10-14 00:49:38',
                'updated_at' => '2022-10-29 02:49:13',
            ),
            46 => 
            array (
                'id' => 54,
                'bom_id' => 20,
                'product_feature_id' => 323,
                'qty' => 0.052500000000000005,
                'consumption' => 0.05,
                'allowance' => 0.0025,
                'unit_price' => 28000.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            47 => 
            array (
                'id' => 55,
                'bom_id' => 20,
                'product_feature_id' => 322,
                'qty' => 0.042,
                'consumption' => 0.04,
                'allowance' => 0.002,
                'unit_price' => 28000.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            48 => 
            array (
                'id' => 58,
                'bom_id' => 20,
                'product_feature_id' => 373,
                'qty' => 0.0315,
                'consumption' => 0.03,
                'allowance' => 0.0015,
                'unit_price' => 28000.0,
                'created_at' => '2022-10-19 06:37:38',
                'updated_at' => '2022-10-19 06:39:16',
            ),
            49 => 
            array (
                'id' => 59,
                'bom_id' => 21,
                'product_feature_id' => 322,
                'qty' => 0.042,
                'consumption' => 0.04,
                'allowance' => 0.002,
                'unit_price' => 28000.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            50 => 
            array (
                'id' => 60,
                'bom_id' => 21,
                'product_feature_id' => 323,
                'qty' => 0.052500000000000005,
                'consumption' => 0.05,
                'allowance' => 0.0025,
                'unit_price' => 28000.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            51 => 
            array (
                'id' => 61,
                'bom_id' => 21,
                'product_feature_id' => 321,
                'qty' => 0.0315,
                'consumption' => 0.03,
                'allowance' => 0.0015,
                'unit_price' => 28000.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            52 => 
            array (
                'id' => 62,
                'bom_id' => 21,
                'product_feature_id' => 152,
                'qty' => 0.3,
                'consumption' => 0.3,
                'allowance' => 0.0,
                'unit_price' => 28000.0,
                'created_at' => '2022-10-19 06:49:03',
                'updated_at' => '2022-10-19 06:49:26',
            ),
            53 => 
            array (
                'id' => 64,
                'bom_id' => 14,
                'product_feature_id' => 373,
                'qty' => 0.043,
                'consumption' => 0.04,
                'allowance' => 0.003,
                'unit_price' => 28000.0,
                'created_at' => '2022-10-23 03:52:38',
                'updated_at' => '2022-10-23 03:53:12',
            ),
            54 => 
            array (
                'id' => 65,
                'bom_id' => 14,
                'product_feature_id' => 323,
                'qty' => 0.06,
                'consumption' => 0.05,
                'allowance' => 0.01,
                'unit_price' => 28000.0,
                'created_at' => '2022-10-23 03:53:55',
                'updated_at' => '2022-10-23 03:54:21',
            ),
            55 => 
            array (
                'id' => 66,
                'bom_id' => 4,
                'product_feature_id' => 120,
                'qty' => 0.0,
                'consumption' => 11.0,
                'allowance' => 5.0,
                'unit_price' => 12000.0,
                'created_at' => '2022-11-16 16:10:26',
                'updated_at' => '2022-11-16 16:10:46',
            ),
            56 => 
            array (
                'id' => 67,
                'bom_id' => 27,
                'product_feature_id' => 151,
                'qty' => 1.32,
                'consumption' => 1.32,
                'allowance' => 0.0,
                'unit_price' => 1000.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            57 => 
            array (
                'id' => 68,
                'bom_id' => 27,
                'product_feature_id' => 152,
                'qty' => 0.2239,
                'consumption' => 0.2132,
                'allowance' => 0.0107,
                'unit_price' => 9500.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            58 => 
            array (
                'id' => 69,
                'bom_id' => 27,
                'product_feature_id' => 153,
                'qty' => 0.052500000000000005,
                'consumption' => 0.05,
                'allowance' => 0.0025,
                'unit_price' => 14000.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            59 => 
            array (
                'id' => 70,
                'bom_id' => 27,
                'product_feature_id' => 154,
                'qty' => 6.3,
                'consumption' => 6.0,
                'allowance' => 0.3,
                'unit_price' => 300.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            60 => 
            array (
                'id' => 71,
                'bom_id' => 27,
                'product_feature_id' => 155,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 800.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            61 => 
            array (
                'id' => 72,
                'bom_id' => 27,
                'product_feature_id' => 156,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 250.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            62 => 
            array (
                'id' => 73,
                'bom_id' => 27,
                'product_feature_id' => 158,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 600.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            63 => 
            array (
                'id' => 74,
                'bom_id' => 27,
                'product_feature_id' => 159,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 1800.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            64 => 
            array (
                'id' => 75,
                'bom_id' => 27,
                'product_feature_id' => 160,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 200.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            65 => 
            array (
                'id' => 76,
                'bom_id' => 27,
                'product_feature_id' => 161,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 700.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            66 => 
            array (
                'id' => 77,
                'bom_id' => 27,
                'product_feature_id' => 162,
                'qty' => 0.042,
                'consumption' => 0.04,
                'allowance' => 0.002,
                'unit_price' => 25000.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            67 => 
            array (
                'id' => 78,
                'bom_id' => 27,
                'product_feature_id' => 163,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 500.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            68 => 
            array (
                'id' => 79,
                'bom_id' => 28,
                'product_feature_id' => 151,
                'qty' => 1.32,
                'consumption' => 1.32,
                'allowance' => 0.0,
                'unit_price' => 1000.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            69 => 
            array (
                'id' => 80,
                'bom_id' => 28,
                'product_feature_id' => 152,
                'qty' => 0.2239,
                'consumption' => 0.2132,
                'allowance' => 0.0107,
                'unit_price' => 9500.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            70 => 
            array (
                'id' => 81,
                'bom_id' => 28,
                'product_feature_id' => 153,
                'qty' => 0.052500000000000005,
                'consumption' => 0.05,
                'allowance' => 0.0025,
                'unit_price' => 14000.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            71 => 
            array (
                'id' => 82,
                'bom_id' => 28,
                'product_feature_id' => 154,
                'qty' => 6.3,
                'consumption' => 6.0,
                'allowance' => 0.3,
                'unit_price' => 300.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            72 => 
            array (
                'id' => 83,
                'bom_id' => 28,
                'product_feature_id' => 155,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 800.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            73 => 
            array (
                'id' => 84,
                'bom_id' => 28,
                'product_feature_id' => 156,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 250.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            74 => 
            array (
                'id' => 85,
                'bom_id' => 28,
                'product_feature_id' => 158,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 600.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            75 => 
            array (
                'id' => 86,
                'bom_id' => 28,
                'product_feature_id' => 159,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 1800.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            76 => 
            array (
                'id' => 87,
                'bom_id' => 28,
                'product_feature_id' => 160,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 200.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            77 => 
            array (
                'id' => 88,
                'bom_id' => 28,
                'product_feature_id' => 161,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 700.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            78 => 
            array (
                'id' => 89,
                'bom_id' => 28,
                'product_feature_id' => 162,
                'qty' => 0.042,
                'consumption' => 0.04,
                'allowance' => 0.002,
                'unit_price' => 25000.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            79 => 
            array (
                'id' => 90,
                'bom_id' => 28,
                'product_feature_id' => 163,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 500.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            80 => 
            array (
                'id' => 91,
                'bom_id' => 29,
                'product_feature_id' => 151,
                'qty' => 1.32,
                'consumption' => 1.32,
                'allowance' => 0.0,
                'unit_price' => 10000.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            81 => 
            array (
                'id' => 92,
                'bom_id' => 29,
                'product_feature_id' => 152,
                'qty' => 0.2239,
                'consumption' => 0.2132,
                'allowance' => 0.0107,
                'unit_price' => 1000.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            82 => 
            array (
                'id' => 93,
                'bom_id' => 29,
                'product_feature_id' => 153,
                'qty' => 0.052500000000000005,
                'consumption' => 0.05,
                'allowance' => 0.0025,
                'unit_price' => 14000.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            83 => 
            array (
                'id' => 94,
                'bom_id' => 29,
                'product_feature_id' => 154,
                'qty' => 6.3,
                'consumption' => 6.0,
                'allowance' => 0.3,
                'unit_price' => 300.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            84 => 
            array (
                'id' => 95,
                'bom_id' => 29,
                'product_feature_id' => 155,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 800.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            85 => 
            array (
                'id' => 96,
                'bom_id' => 29,
                'product_feature_id' => 156,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 250.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            86 => 
            array (
                'id' => 97,
                'bom_id' => 29,
                'product_feature_id' => 158,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 600.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            87 => 
            array (
                'id' => 98,
                'bom_id' => 29,
                'product_feature_id' => 159,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 1800.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            88 => 
            array (
                'id' => 99,
                'bom_id' => 29,
                'product_feature_id' => 160,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 200.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            89 => 
            array (
                'id' => 100,
                'bom_id' => 29,
                'product_feature_id' => 161,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 700.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            90 => 
            array (
                'id' => 101,
                'bom_id' => 29,
                'product_feature_id' => 162,
                'qty' => 0.042,
                'consumption' => 0.04,
                'allowance' => 0.002,
                'unit_price' => 25000.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            91 => 
            array (
                'id' => 102,
                'bom_id' => 29,
                'product_feature_id' => 163,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 500.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            92 => 
            array (
                'id' => 103,
                'bom_id' => 30,
                'product_feature_id' => 151,
                'qty' => 1.32,
                'consumption' => 1.32,
                'allowance' => 0.0,
                'unit_price' => 1000.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            93 => 
            array (
                'id' => 104,
                'bom_id' => 30,
                'product_feature_id' => 152,
                'qty' => 0.2239,
                'consumption' => 0.2132,
                'allowance' => 0.0107,
                'unit_price' => 1000.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            94 => 
            array (
                'id' => 105,
                'bom_id' => 30,
                'product_feature_id' => 153,
                'qty' => 0.052500000000000005,
                'consumption' => 0.05,
                'allowance' => 0.0025,
                'unit_price' => 14000.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            95 => 
            array (
                'id' => 106,
                'bom_id' => 30,
                'product_feature_id' => 154,
                'qty' => 6.3,
                'consumption' => 6.0,
                'allowance' => 0.3,
                'unit_price' => 300.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            96 => 
            array (
                'id' => 107,
                'bom_id' => 30,
                'product_feature_id' => 155,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 800.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            97 => 
            array (
                'id' => 108,
                'bom_id' => 30,
                'product_feature_id' => 156,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 250.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            98 => 
            array (
                'id' => 109,
                'bom_id' => 30,
                'product_feature_id' => 158,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 600.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            99 => 
            array (
                'id' => 110,
                'bom_id' => 30,
                'product_feature_id' => 159,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 1800.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            100 => 
            array (
                'id' => 111,
                'bom_id' => 30,
                'product_feature_id' => 160,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 200.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            101 => 
            array (
                'id' => 112,
                'bom_id' => 30,
                'product_feature_id' => 161,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 700.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            102 => 
            array (
                'id' => 113,
                'bom_id' => 30,
                'product_feature_id' => 162,
                'qty' => 0.042,
                'consumption' => 0.04,
                'allowance' => 0.002,
                'unit_price' => 25000.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            103 => 
            array (
                'id' => 114,
                'bom_id' => 30,
                'product_feature_id' => 163,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 500.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            104 => 
            array (
                'id' => 115,
                'bom_id' => 31,
                'product_feature_id' => 165,
                'qty' => 1.35,
                'consumption' => 1.35,
                'allowance' => 0.0,
                'unit_price' => 1000.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            105 => 
            array (
                'id' => 116,
                'bom_id' => 31,
                'product_feature_id' => 152,
                'qty' => 0.2242,
                'consumption' => 0.2132,
                'allowance' => 0.011,
                'unit_price' => 9500.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            106 => 
            array (
                'id' => 117,
                'bom_id' => 31,
                'product_feature_id' => 153,
                'qty' => 0.052500000000000005,
                'consumption' => 0.05,
                'allowance' => 0.0025,
                'unit_price' => 14000.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            107 => 
            array (
                'id' => 118,
                'bom_id' => 31,
                'product_feature_id' => 154,
                'qty' => 6.3,
                'consumption' => 6.0,
                'allowance' => 0.3,
                'unit_price' => 300.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            108 => 
            array (
                'id' => 119,
                'bom_id' => 31,
                'product_feature_id' => 155,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 800.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            109 => 
            array (
                'id' => 120,
                'bom_id' => 31,
                'product_feature_id' => 156,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 250.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            110 => 
            array (
                'id' => 121,
                'bom_id' => 31,
                'product_feature_id' => 158,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 600.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            111 => 
            array (
                'id' => 122,
                'bom_id' => 31,
                'product_feature_id' => 159,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 1800.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            112 => 
            array (
                'id' => 123,
                'bom_id' => 31,
                'product_feature_id' => 160,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 200.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            113 => 
            array (
                'id' => 124,
                'bom_id' => 31,
                'product_feature_id' => 161,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 700.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            114 => 
            array (
                'id' => 125,
                'bom_id' => 31,
                'product_feature_id' => 162,
                'qty' => 0.042,
                'consumption' => 0.04,
                'allowance' => 0.002,
                'unit_price' => 25000.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            115 => 
            array (
                'id' => 126,
                'bom_id' => 31,
                'product_feature_id' => 163,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 500.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            116 => 
            array (
                'id' => 127,
                'bom_id' => 32,
                'product_feature_id' => 165,
                'qty' => 1.35,
                'consumption' => 1.35,
                'allowance' => 0.0,
                'unit_price' => 1000.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            117 => 
            array (
                'id' => 128,
                'bom_id' => 32,
                'product_feature_id' => 152,
                'qty' => 0.2242,
                'consumption' => 0.2132,
                'allowance' => 0.011,
                'unit_price' => 9500.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            118 => 
            array (
                'id' => 129,
                'bom_id' => 32,
                'product_feature_id' => 153,
                'qty' => 0.052500000000000005,
                'consumption' => 0.05,
                'allowance' => 0.0025,
                'unit_price' => 14000.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            119 => 
            array (
                'id' => 130,
                'bom_id' => 32,
                'product_feature_id' => 154,
                'qty' => 6.3,
                'consumption' => 6.0,
                'allowance' => 0.3,
                'unit_price' => 300.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            120 => 
            array (
                'id' => 131,
                'bom_id' => 32,
                'product_feature_id' => 155,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 800.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            121 => 
            array (
                'id' => 132,
                'bom_id' => 32,
                'product_feature_id' => 156,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 250.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            122 => 
            array (
                'id' => 133,
                'bom_id' => 32,
                'product_feature_id' => 158,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 600.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            123 => 
            array (
                'id' => 134,
                'bom_id' => 32,
                'product_feature_id' => 159,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 1800.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            124 => 
            array (
                'id' => 135,
                'bom_id' => 32,
                'product_feature_id' => 160,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 200.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            125 => 
            array (
                'id' => 136,
                'bom_id' => 32,
                'product_feature_id' => 161,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 700.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            126 => 
            array (
                'id' => 137,
                'bom_id' => 32,
                'product_feature_id' => 162,
                'qty' => 0.042,
                'consumption' => 0.04,
                'allowance' => 0.002,
                'unit_price' => 25000.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            127 => 
            array (
                'id' => 138,
                'bom_id' => 32,
                'product_feature_id' => 163,
                'qty' => 1.05,
                'consumption' => 1.0,
                'allowance' => 0.05,
                'unit_price' => 500.0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}