<?php

use Illuminate\Database\Seeder;

class BomTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('bom')->delete();
        
        \DB::table('bom')->insert(array (
            0 => 
            array (
                'id' => 2,
                'party_id' => NULL,
                'product_id' => 53,
                'product_feature_id' => NULL,
                'name' => 'BIENSI-STYLE3-LINE1',
                'qty' => 10260,
                'margin' => 15.0,
                'starting_price' => NULL,
                'final_price' => 144242.0,
                'tax' => 11.0,
                'company_name' => 'PT BSI',
                'start_date' => '2022-10-01',
                'end_date' => '2022-10-28',
                'created_at' => '2022-09-22 01:28:09',
                'updated_at' => '2022-10-06 03:10:57',
            ),
            1 => 
            array (
                'id' => 3,
                'party_id' => NULL,
                'product_id' => 37,
                'product_feature_id' => NULL,
                'name' => 'BIENSI-STYLE6-LINE2',
                'qty' => 3420,
                'margin' => 15.0,
                'starting_price' => NULL,
                'final_price' => 141252.0,
                'tax' => 0.0,
                'company_name' => 'PT BSI',
                'start_date' => '2022-09-22',
                'end_date' => '2022-09-30',
                'created_at' => '2022-09-22 01:44:58',
                'updated_at' => '2022-10-06 03:11:33',
            ),
            2 => 
            array (
                'id' => 4,
                'party_id' => NULL,
                'product_id' => 57,
                'product_feature_id' => NULL,
                'name' => 'TOMTAYLOR_BIENSI',
                'qty' => 3240,
                'margin' => 35.1252,
                'starting_price' => 100007.0,
                'final_price' => 111000.0,
                'tax' => 11.0,
                'company_name' => 'PT. HARUS DUA EMPAT',
                'start_date' => '2022-12-15',
                'end_date' => '2023-01-10',
                'created_at' => '2022-10-04 04:20:51',
                'updated_at' => '2022-11-14 05:32:00',
            ),
            3 => 
            array (
                'id' => 8,
                'party_id' => 2,
                'product_id' => 64,
                'product_feature_id' => NULL,
                'name' => 'Cressida Menshirt',
                'qty' => 21000,
                'margin' => 25.0,
                'starting_price' => 18000.0,
                'final_price' => 19000.0,
                'tax' => 11.0,
                'company_name' => 'PT BSI',
                'start_date' => '2022-10-14',
                'end_date' => '2022-10-31',
                'created_at' => '2022-10-05 02:21:08',
                'updated_at' => '2022-11-14 05:37:38',
            ),
            4 => 
            array (
                'id' => 9,
                'party_id' => NULL,
                'product_id' => 62,
                'product_feature_id' => NULL,
                'name' => 'COSTING-DAREN',
                'qty' => 937,
                'margin' => 10.0,
                'starting_price' => NULL,
                'final_price' => 34000.0,
                'tax' => 11.0,
                'company_name' => 'PT BSI',
                'start_date' => '2022-10-01',
                'end_date' => '2022-10-25',
                'created_at' => '2022-10-05 03:24:01',
                'updated_at' => '2022-10-06 02:59:33',
            ),
            5 => 
            array (
                'id' => 10,
                'party_id' => NULL,
                'product_id' => 61,
                'product_feature_id' => NULL,
                'name' => 'COSTING-EDDIE',
                'qty' => 1604,
                'margin' => -10.4,
                'starting_price' => NULL,
                'final_price' => 32000.0,
                'tax' => 11.0,
                'company_name' => 'PT BSI',
                'start_date' => '2022-10-01',
                'end_date' => '2022-10-25',
                'created_at' => '2022-10-05 03:24:39',
                'updated_at' => '2022-10-19 08:38:22',
            ),
            6 => 
            array (
                'id' => 11,
                'party_id' => NULL,
                'product_id' => 61,
                'product_feature_id' => NULL,
                'name' => 'COSTING-DEVANO',
                'qty' => 950,
                'margin' => 3.6,
                'starting_price' => NULL,
                'final_price' => 37000.0,
                'tax' => 11.0,
                'company_name' => 'PT BSI',
                'start_date' => '2022-10-01',
                'end_date' => '2022-10-25',
                'created_at' => '2022-10-05 03:25:31',
                'updated_at' => '2022-10-19 08:39:28',
            ),
            7 => 
            array (
                'id' => 12,
                'party_id' => NULL,
                'product_id' => 87,
                'product_feature_id' => NULL,
                'name' => 'EMBA-DEON.2',
                'qty' => 3000,
                'margin' => -10.0719,
                'starting_price' => NULL,
                'final_price' => 20000.0,
                'tax' => 11.0,
                'company_name' => 'PT Buana Sandang Indonesia',
                'start_date' => '2022-10-18',
                'end_date' => '2022-10-25',
                'created_at' => '2022-10-13 03:14:27',
                'updated_at' => '2022-10-19 08:34:00',
            ),
            8 => 
            array (
                'id' => 13,
                'party_id' => 2,
                'product_id' => 87,
                'product_feature_id' => NULL,
                'name' => 'EMBA-DEON.2-Ver-2',
                'qty' => 3000,
                'margin' => 7.42934,
                'starting_price' => NULL,
                'final_price' => 22500.0,
                'tax' => 11.0,
                'company_name' => 'PT Buana Sandang Indonesia',
                'start_date' => '2022-10-08',
                'end_date' => '2022-10-18',
                'created_at' => '2022-10-13 03:17:14',
                'updated_at' => '2022-10-24 07:03:59',
            ),
            9 => 
            array (
                'id' => 14,
                'party_id' => NULL,
                'product_id' => 90,
                'product_feature_id' => NULL,
                'name' => 'EMBA_SPRINGBOX AND TOMSKY',
                'qty' => 18422,
                'margin' => 0.0,
                'starting_price' => NULL,
                'final_price' => 34000.0,
                'tax' => 11.0,
                'company_name' => 'PT Buana Sandang Indonesia',
                'start_date' => '2022-10-18',
                'end_date' => '2022-10-31',
                'created_at' => '2022-10-14 00:25:08',
                'updated_at' => '2022-10-14 00:25:08',
            ),
            10 => 
            array (
                'id' => 16,
                'party_id' => 3,
                'product_id' => 175,
                'product_feature_id' => NULL,
                'name' => 'II-AOI_T797_T785_T796_T819_S169_NOV\'22',
                'qty' => 2021,
                'margin' => 10.3475,
                'starting_price' => NULL,
                'final_price' => 73565.0,
                'tax' => 11.0,
                'company_name' => 'PT Buana Sandang Indonesia',
                'start_date' => '2022-11-04',
                'end_date' => '2022-11-15',
                'created_at' => '2022-10-18 05:12:43',
                'updated_at' => '2022-10-23 03:42:48',
            ),
            11 => 
            array (
                'id' => 17,
                'party_id' => 16,
                'product_id' => 177,
                'product_feature_id' => NULL,
                'name' => 'I_ISG_Celana_Okt_2022',
                'qty' => 5000,
                'margin' => 25.0,
                'starting_price' => NULL,
                'final_price' => 25000.0,
                'tax' => 11.0,
                'company_name' => 'PT. Buana Sandang Indonesia',
                'start_date' => '2022-10-18',
                'end_date' => '2022-10-29',
                'created_at' => '2022-10-18 08:50:01',
                'updated_at' => '2022-10-23 03:43:08',
            ),
            12 => 
            array (
                'id' => 18,
                'party_id' => 16,
                'product_id' => 177,
                'product_feature_id' => NULL,
                'name' => 'II_ISG_Celana_Okt_2022',
                'qty' => 5000,
                'margin' => 0.0,
                'starting_price' => NULL,
                'final_price' => 25000.0,
                'tax' => 11.0,
                'company_name' => 'PT Buana Sandang Indonesia',
                'start_date' => '2022-10-18',
                'end_date' => '2022-10-28',
                'created_at' => '2022-10-19 04:55:07',
                'updated_at' => '2022-10-23 03:43:26',
            ),
            13 => 
            array (
                'id' => 20,
                'party_id' => 2,
                'product_id' => 185,
                'product_feature_id' => NULL,
                'name' => 'I_EMBA_CELANA_FINSLEY&EAGLE&GATES_Nov\'22',
                'qty' => 1724,
                'margin' => -10.4753,
                'starting_price' => NULL,
                'final_price' => 33000.0,
                'tax' => 11.0,
                'company_name' => 'PT Buana Sandang Indonesia',
                'start_date' => '2022-11-01',
                'end_date' => '2022-11-12',
                'created_at' => '2022-10-19 06:34:04',
                'updated_at' => '2022-10-24 07:02:04',
            ),
            14 => 
            array (
                'id' => 21,
                'party_id' => 2,
                'product_id' => 188,
                'product_feature_id' => NULL,
                'name' => 'I_EMBA_JAKET_Winslow&Pegasus-Nov\'22',
                'qty' => 1402,
                'margin' => -11.6243,
                'starting_price' => NULL,
                'final_price' => 40000.0,
                'tax' => 11.0,
                'company_name' => 'PT Buana Sandang Indonesia',
                'start_date' => '2022-11-01',
                'end_date' => '2022-11-07',
                'created_at' => '2022-10-19 06:48:43',
                'updated_at' => '2022-10-23 03:42:36',
            ),
            15 => 
            array (
                'id' => 23,
                'party_id' => 16,
                'product_id' => 234,
                'product_feature_id' => NULL,
                'name' => 'I-ISG_JOEYRIDA_OKT-22',
                'qty' => 8468,
                'margin' => 0.0,
                'starting_price' => NULL,
                'final_price' => NULL,
                'tax' => 11.0,
                'company_name' => 'PT Buana Sandang Indonesia',
                'start_date' => '2022-10-01',
                'end_date' => '2022-11-22',
                'created_at' => '2022-10-26 07:15:21',
                'updated_at' => '2022-10-26 07:15:21',
            ),
            16 => 
            array (
                'id' => 25,
                'party_id' => 16,
                'product_id' => 234,
                'product_feature_id' => NULL,
                'name' => 'III_ISG_JOEYRIDA-OKT-22',
                'qty' => 8468,
                'margin' => 30.909090909090903,
                'starting_price' => NULL,
                'final_price' => 30000.0,
                'tax' => 11.0,
                'company_name' => 'PT Buana Sandang Indonesia',
                'start_date' => '2022-11-01',
                'end_date' => '2022-11-23',
                'created_at' => '2022-10-26 07:21:00',
                'updated_at' => '2022-11-02 02:48:10',
            ),
            17 => 
            array (
                'id' => 26,
                'party_id' => 7,
                'product_id' => 7,
                'product_feature_id' => NULL,
                'name' => 'KKS Emba',
                'qty' => 10000,
                'margin' => 0.0,
                'starting_price' => 19999.0,
                'final_price' => NULL,
                'tax' => 11.0,
                'company_name' => 'PT Buana Sandang Indonesia',
                'start_date' => '2022-11-17',
                'end_date' => '2022-11-15',
                'created_at' => '2022-11-23 13:37:37',
                'updated_at' => '2022-11-23 13:37:37',
            ),
            18 => 
            array (
                'id' => 27,
                'party_id' => 7,
                'product_id' => 7,
                'product_feature_id' => NULL,
                'name' => 'Service1',
                'qty' => 12000,
                'margin' => 0.0,
                'starting_price' => 110000.0,
                'final_price' => NULL,
                'tax' => 11.0,
                'company_name' => 'PT Buana Sandang Indonesia',
                'start_date' => '2022-12-22',
                'end_date' => '2023-01-06',
                'created_at' => '2022-12-03 05:39:40',
                'updated_at' => '2022-12-03 05:39:40',
            ),
            19 => 
            array (
                'id' => 28,
                'party_id' => 7,
                'product_id' => 7,
                'product_feature_id' => NULL,
                'name' => 'Service1',
                'qty' => 12000,
                'margin' => 0.0,
                'starting_price' => 110000.0,
                'final_price' => NULL,
                'tax' => 11.0,
                'company_name' => 'PT Buana Sandang Indonesia',
                'start_date' => '2022-12-22',
                'end_date' => '2023-01-06',
                'created_at' => '2022-12-03 05:39:51',
                'updated_at' => '2022-12-03 05:39:51',
            ),
            20 => 
            array (
                'id' => 29,
                'party_id' => 7,
                'product_id' => 8,
                'product_feature_id' => NULL,
                'name' => 'T3-20/2',
                'qty' => 12000,
                'margin' => 0.0,
                'starting_price' => 120000.0,
                'final_price' => NULL,
                'tax' => 11.0,
                'company_name' => 'PT Buana Sandang Indonesia',
                'start_date' => '2022-12-16',
                'end_date' => '2023-01-07',
                'created_at' => '2022-12-03 05:47:41',
                'updated_at' => '2022-12-03 05:47:41',
            ),
            21 => 
            array (
                'id' => 30,
                'party_id' => 7,
                'product_id' => 8,
                'product_feature_id' => NULL,
                'name' => 'T3-20/2',
                'qty' => 12000,
                'margin' => 0.0,
                'starting_price' => 120000.0,
                'final_price' => NULL,
                'tax' => 11.0,
                'company_name' => 'PT Buana Sandang Indonesia',
                'start_date' => '2022-12-16',
                'end_date' => '2023-01-07',
                'created_at' => '2022-12-03 05:48:36',
                'updated_at' => '2022-12-03 05:48:36',
            ),
            22 => 
            array (
                'id' => 31,
                'party_id' => 1,
                'product_id' => 8,
                'product_feature_id' => NULL,
                'name' => 'BIENSI-STYLE3-LINE1',
                'qty' => 1200,
                'margin' => 0.0,
                'starting_price' => 0.0,
                'final_price' => NULL,
                'tax' => 11.0,
                'company_name' => 'PT Buana Sandang Indonesia',
                'start_date' => '2022-12-14',
                'end_date' => '2023-01-04',
                'created_at' => '2022-12-03 05:50:26',
                'updated_at' => '2022-12-03 05:50:26',
            ),
            23 => 
            array (
                'id' => 32,
                'party_id' => 1,
                'product_id' => 9,
                'product_feature_id' => NULL,
                'name' => 'NUXVER',
                'qty' => 1200,
                'margin' => 0.0,
                'starting_price' => 0.0,
                'final_price' => NULL,
                'tax' => 11.0,
                'company_name' => 'PT Buana Sandang Indonesia',
                'start_date' => '2022-12-08',
                'end_date' => '2022-12-29',
                'created_at' => '2022-12-03 05:54:02',
                'updated_at' => '2022-12-03 05:54:47',
            ),
        ));
        
        
    }
}