<?php

use Illuminate\Database\Seeder;

class MonitoringBsiCuttingTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('monitoring_bsi_cutting')->delete();
        
        \DB::table('monitoring_bsi_cutting')->insert(array (
            0 => 
            array (
                'id' => 8,
                'spread_id' => 0,
                'date' => '2022-10-20',
                'po_number' => '1',
                'sales_order_id' => 17,
                'order_id' => 27,
                'order_item_id' => 187,
                'product_feature_id' => 259,
                'category_name' => NULL,
                'output' => 293,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'id' => 9,
                'spread_id' => 0,
                'date' => '2022-10-20',
                'po_number' => '1',
                'sales_order_id' => 17,
                'order_id' => 27,
                'order_item_id' => 188,
                'product_feature_id' => 260,
                'category_name' => NULL,
                'output' => 234,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'id' => 10,
                'spread_id' => 0,
                'date' => '2022-10-20',
                'po_number' => '1',
                'sales_order_id' => 17,
                'order_id' => 27,
                'order_item_id' => 189,
                'product_feature_id' => 261,
                'category_name' => NULL,
                'output' => 190,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'id' => 11,
                'spread_id' => 0,
                'date' => '2022-10-21',
                'po_number' => '1',
                'sales_order_id' => 22,
                'order_id' => 33,
                'order_item_id' => 268,
                'product_feature_id' => 359,
                'category_name' => NULL,
                'output' => 350,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'id' => 12,
                'spread_id' => 0,
                'date' => '2022-10-21',
                'po_number' => '1',
                'sales_order_id' => 22,
                'order_id' => 33,
                'order_item_id' => 265,
                'product_feature_id' => 356,
                'category_name' => NULL,
                'output' => 175,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'id' => 13,
                'spread_id' => 0,
                'date' => '2022-10-21',
                'po_number' => '1',
                'sales_order_id' => 22,
                'order_id' => 33,
                'order_item_id' => 272,
                'product_feature_id' => 362,
                'category_name' => NULL,
                'output' => 350,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'id' => 14,
                'spread_id' => 0,
                'date' => '2022-10-21',
                'po_number' => '1',
                'sales_order_id' => 22,
                'order_id' => 33,
                'order_item_id' => 274,
                'product_feature_id' => 365,
                'category_name' => NULL,
                'output' => 175,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'id' => 15,
                'spread_id' => 0,
                'date' => '2022-10-22',
                'po_number' => '1',
                'sales_order_id' => 17,
                'order_id' => 27,
                'order_item_id' => 188,
                'product_feature_id' => 260,
                'category_name' => NULL,
                'output' => 190,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'id' => 16,
                'spread_id' => 0,
                'date' => '2022-10-24',
                'po_number' => '1',
                'sales_order_id' => 17,
                'order_id' => 27,
                'order_item_id' => 187,
                'product_feature_id' => 259,
                'category_name' => NULL,
                'output' => 143,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'id' => 17,
                'spread_id' => 0,
                'date' => '2022-10-24',
                'po_number' => '1',
                'sales_order_id' => 17,
                'order_id' => 27,
                'order_item_id' => 189,
                'product_feature_id' => 261,
                'category_name' => NULL,
                'output' => 143,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'id' => 18,
                'spread_id' => 0,
                'date' => '2022-10-24',
                'po_number' => '2c063',
                'sales_order_id' => 22,
                'order_id' => 33,
                'order_item_id' => 265,
                'product_feature_id' => 356,
                'category_name' => NULL,
                'output' => 57,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'id' => 19,
                'spread_id' => 0,
                'date' => '2022-10-24',
                'po_number' => '2c063',
                'sales_order_id' => 22,
                'order_id' => 33,
                'order_item_id' => 268,
                'product_feature_id' => 359,
                'category_name' => NULL,
                'output' => 114,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'id' => 20,
                'spread_id' => 0,
                'date' => '2022-10-24',
                'po_number' => '2c063',
                'sales_order_id' => 22,
                'order_id' => 33,
                'order_item_id' => 272,
                'product_feature_id' => 362,
                'category_name' => NULL,
                'output' => 114,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'id' => 21,
                'spread_id' => 0,
                'date' => '2022-10-24',
                'po_number' => '2c063',
                'sales_order_id' => 22,
                'order_id' => 33,
                'order_item_id' => 274,
                'product_feature_id' => 365,
                'category_name' => NULL,
                'output' => 57,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'id' => 22,
                'spread_id' => 0,
                'date' => '2022-10-25',
                'po_number' => '1',
                'sales_order_id' => 17,
                'order_id' => 27,
                'order_item_id' => 187,
                'product_feature_id' => 259,
                'category_name' => NULL,
                'output' => 76,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'id' => 23,
                'spread_id' => 0,
                'date' => '2022-10-25',
                'po_number' => '1',
                'sales_order_id' => 17,
                'order_id' => 27,
                'order_item_id' => 188,
                'product_feature_id' => 260,
                'category_name' => NULL,
                'output' => 178,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'id' => 24,
                'spread_id' => 0,
                'date' => '2022-10-25',
                'po_number' => '1',
                'sales_order_id' => 17,
                'order_id' => 27,
                'order_item_id' => 189,
                'product_feature_id' => 261,
                'category_name' => NULL,
                'output' => 186,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'id' => 25,
                'spread_id' => 0,
                'date' => '2022-10-25',
                'po_number' => '1',
                'sales_order_id' => 17,
                'order_id' => 27,
                'order_item_id' => 189,
                'product_feature_id' => 261,
                'category_name' => NULL,
                'output' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'id' => 26,
                'spread_id' => 0,
                'date' => '2022-10-27',
                'po_number' => 'bs6/cs6',
                'sales_order_id' => 25,
                'order_id' => 36,
                'order_item_id' => 404,
                'product_feature_id' => 638,
                'category_name' => NULL,
                'output' => 338,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'id' => 27,
                'spread_id' => 0,
                'date' => '2022-10-27',
                'po_number' => 'bs6/cs6',
                'sales_order_id' => 25,
                'order_id' => 36,
                'order_item_id' => 405,
                'product_feature_id' => 639,
                'category_name' => NULL,
                'output' => 420,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'id' => 28,
                'spread_id' => 0,
                'date' => '2022-10-27',
                'po_number' => 'bs6/cs6',
                'sales_order_id' => 25,
                'order_id' => 36,
                'order_item_id' => 406,
                'product_feature_id' => 640,
                'category_name' => NULL,
                'output' => 382,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'id' => 34,
                'spread_id' => 0,
                'date' => '2022-10-27',
                'po_number' => '2c063',
                'sales_order_id' => 22,
                'order_id' => 33,
                'order_item_id' => 265,
                'product_feature_id' => 356,
                'category_name' => NULL,
                'output' => 12,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'id' => 35,
                'spread_id' => 0,
                'date' => '2022-10-27',
                'po_number' => '2c063',
                'sales_order_id' => 22,
                'order_id' => 33,
                'order_item_id' => 268,
                'product_feature_id' => 359,
                'category_name' => NULL,
                'output' => 28,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'id' => 36,
                'spread_id' => 0,
                'date' => '2022-10-27',
                'po_number' => '2c063',
                'sales_order_id' => 22,
                'order_id' => 33,
                'order_item_id' => 272,
                'product_feature_id' => 362,
                'category_name' => NULL,
                'output' => 28,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'id' => 37,
                'spread_id' => 0,
                'date' => '2022-10-27',
                'po_number' => '2c063',
                'sales_order_id' => 22,
                'order_id' => 33,
                'order_item_id' => 274,
                'product_feature_id' => 365,
                'category_name' => NULL,
                'output' => 16,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'id' => 38,
                'spread_id' => 0,
                'date' => '2022-10-27',
                'po_number' => '2c061',
                'sales_order_id' => 22,
                'order_id' => 33,
                'order_item_id' => 263,
                'product_feature_id' => 354,
                'category_name' => NULL,
                'output' => 110,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            26 => 
            array (
                'id' => 39,
                'spread_id' => 0,
                'date' => '2022-10-27',
                'po_number' => '2c061',
                'sales_order_id' => 22,
                'order_id' => 33,
                'order_item_id' => 266,
                'product_feature_id' => 357,
                'category_name' => NULL,
                'output' => 220,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            27 => 
            array (
                'id' => 40,
                'spread_id' => 0,
                'date' => '2022-10-27',
                'po_number' => '2c061',
                'sales_order_id' => 22,
                'order_id' => 33,
                'order_item_id' => 269,
                'product_feature_id' => 360,
                'category_name' => NULL,
                'output' => 220,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            28 => 
            array (
                'id' => 41,
                'spread_id' => 0,
                'date' => '2022-10-27',
                'po_number' => '2c061',
                'sales_order_id' => 22,
                'order_id' => 33,
                'order_item_id' => 271,
                'product_feature_id' => 363,
                'category_name' => NULL,
                'output' => 110,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            29 => 
            array (
                'id' => 42,
                'spread_id' => 0,
                'date' => '2022-10-29',
                'po_number' => 'CS 25',
                'sales_order_id' => 24,
                'order_id' => 35,
                'order_item_id' => 402,
                'product_feature_id' => 642,
                'category_name' => NULL,
                'output' => 280,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            30 => 
            array (
                'id' => 43,
                'spread_id' => 0,
                'date' => '2022-10-29',
                'po_number' => '2C061',
                'sales_order_id' => 22,
                'order_id' => 33,
                'order_item_id' => 263,
                'product_feature_id' => 354,
                'category_name' => NULL,
                'output' => 55,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            31 => 
            array (
                'id' => 44,
                'spread_id' => 0,
                'date' => '2022-10-29',
                'po_number' => '2C061',
                'sales_order_id' => 22,
                'order_id' => 33,
                'order_item_id' => 266,
                'product_feature_id' => 357,
                'category_name' => NULL,
                'output' => 110,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            32 => 
            array (
                'id' => 45,
                'spread_id' => 0,
                'date' => '2022-10-29',
                'po_number' => '2C061',
                'sales_order_id' => 22,
                'order_id' => 33,
                'order_item_id' => 269,
                'product_feature_id' => 360,
                'category_name' => NULL,
                'output' => 110,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            33 => 
            array (
                'id' => 46,
                'spread_id' => 0,
                'date' => '2022-10-29',
                'po_number' => '2C061',
                'sales_order_id' => 22,
                'order_id' => 33,
                'order_item_id' => 271,
                'product_feature_id' => 363,
                'category_name' => NULL,
                'output' => 55,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            34 => 
            array (
                'id' => 47,
                'spread_id' => 0,
                'date' => '2023-01-04',
                'po_number' => '00',
                'sales_order_id' => 3,
                'order_id' => 3,
                'order_item_id' => 8,
                'product_feature_id' => 16,
                'category_name' => NULL,
                'output' => 10,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            35 => 
            array (
                'id' => 48,
                'spread_id' => 0,
                'date' => '2022-12-21',
                'po_number' => '22',
                'sales_order_id' => 34,
                'order_id' => 45,
                'order_item_id' => 1,
                'product_feature_id' => 469,
                'category_name' => NULL,
                'output' => 10,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            36 => 
            array (
                'id' => 49,
                'spread_id' => 0,
                'date' => '2022-12-21',
                'po_number' => '22',
                'sales_order_id' => 34,
                'order_id' => 45,
                'order_item_id' => 2,
                'product_feature_id' => 676,
                'category_name' => NULL,
                'output' => 10,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}