<?php

use Illuminate\Database\Seeder;

class QuoteItemTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('quote_item')->delete();
        
        \DB::table('quote_item')->insert(array (
            0 => 
            array (
                'id' => 4,
                'quote_id' => 2,
                'request_item_id' => NULL,
                'product_feature_id' => 15,
                'qty' => 100,
                'unit_price' => '2000',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'id' => 5,
                'quote_id' => 2,
                'request_item_id' => NULL,
                'product_feature_id' => 16,
                'qty' => 100,
                'unit_price' => '2000',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'id' => 8,
                'quote_id' => 2,
                'request_item_id' => NULL,
                'product_feature_id' => 17,
                'qty' => 100,
                'unit_price' => '2000',
                'created_at' => NULL,
                'updated_at' => '2022-09-04 15:47:54',
            ),
            3 => 
            array (
                'id' => 9,
                'quote_id' => 3,
                'request_item_id' => NULL,
                'product_feature_id' => 15,
                'qty' => 300,
                'unit_price' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'id' => 10,
                'quote_id' => 3,
                'request_item_id' => NULL,
                'product_feature_id' => 16,
                'qty' => 300,
                'unit_price' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'id' => 11,
                'quote_id' => 3,
                'request_item_id' => NULL,
                'product_feature_id' => 17,
                'qty' => 300,
                'unit_price' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'id' => 12,
                'quote_id' => 4,
                'request_item_id' => NULL,
                'product_feature_id' => 15,
                'qty' => 600,
                'unit_price' => '0',
                'created_at' => NULL,
                'updated_at' => '2022-09-04 16:44:05',
            ),
            7 => 
            array (
                'id' => 13,
                'quote_id' => 4,
                'request_item_id' => NULL,
                'product_feature_id' => 16,
                'qty' => 600,
                'unit_price' => '0',
                'created_at' => NULL,
                'updated_at' => '2022-09-04 16:44:11',
            ),
            8 => 
            array (
                'id' => 14,
                'quote_id' => 4,
                'request_item_id' => NULL,
                'product_feature_id' => 17,
                'qty' => 600,
                'unit_price' => '0',
                'created_at' => NULL,
                'updated_at' => '2022-09-04 16:44:16',
            ),
            9 => 
            array (
                'id' => 19,
                'quote_id' => 5,
                'request_item_id' => NULL,
                'product_feature_id' => 9,
                'qty' => 100,
                'unit_price' => '2000',
                'created_at' => NULL,
                'updated_at' => '2022-09-08 14:54:54',
            ),
            10 => 
            array (
                'id' => 20,
                'quote_id' => 5,
                'request_item_id' => NULL,
                'product_feature_id' => 11,
                'qty' => 100,
                'unit_price' => '2000',
                'created_at' => NULL,
                'updated_at' => '2022-09-08 14:54:54',
            ),
            11 => 
            array (
                'id' => 21,
                'quote_id' => 5,
                'request_item_id' => NULL,
                'product_feature_id' => 12,
                'qty' => 100,
                'unit_price' => '2000',
                'created_at' => NULL,
                'updated_at' => '2022-09-08 14:54:54',
            ),
            12 => 
            array (
                'id' => 22,
                'quote_id' => 5,
                'request_item_id' => NULL,
                'product_feature_id' => 10,
                'qty' => 100,
                'unit_price' => '2000',
                'created_at' => NULL,
                'updated_at' => '2022-09-08 14:54:54',
            ),
            13 => 
            array (
                'id' => 23,
                'quote_id' => 6,
                'request_item_id' => NULL,
                'product_feature_id' => 84,
                'qty' => 100,
                'unit_price' => '59322',
                'created_at' => NULL,
                'updated_at' => '2022-09-09 02:48:39',
            ),
            14 => 
            array (
                'id' => 24,
                'quote_id' => 6,
                'request_item_id' => NULL,
                'product_feature_id' => 85,
                'qty' => 150,
                'unit_price' => '59322',
                'created_at' => NULL,
                'updated_at' => '2022-09-09 02:48:47',
            ),
            15 => 
            array (
                'id' => 25,
                'quote_id' => 6,
                'request_item_id' => NULL,
                'product_feature_id' => 86,
                'qty' => 500,
                'unit_price' => '59322',
                'created_at' => NULL,
                'updated_at' => '2022-09-09 02:49:02',
            ),
            16 => 
            array (
                'id' => 26,
                'quote_id' => 6,
                'request_item_id' => NULL,
                'product_feature_id' => 87,
                'qty' => 275,
                'unit_price' => '59322',
                'created_at' => NULL,
                'updated_at' => '2022-09-09 02:49:08',
            ),
            17 => 
            array (
                'id' => 27,
                'quote_id' => 6,
                'request_item_id' => NULL,
                'product_feature_id' => 88,
                'qty' => 50,
                'unit_price' => '59322',
                'created_at' => NULL,
                'updated_at' => '2022-09-09 02:49:18',
            ),
            18 => 
            array (
                'id' => 28,
                'quote_id' => 6,
                'request_item_id' => NULL,
                'product_feature_id' => 89,
                'qty' => 20,
                'unit_price' => '59322',
                'created_at' => NULL,
                'updated_at' => '2022-09-09 02:49:30',
            ),
            19 => 
            array (
                'id' => 29,
                'quote_id' => 6,
                'request_item_id' => NULL,
                'product_feature_id' => 90,
                'qty' => 5,
                'unit_price' => '59322',
                'created_at' => NULL,
                'updated_at' => '2022-09-09 02:49:24',
            ),
            20 => 
            array (
                'id' => 30,
                'quote_id' => 7,
                'request_item_id' => NULL,
                'product_feature_id' => 50,
                'qty' => 200,
                'unit_price' => '59292',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'id' => 31,
                'quote_id' => 7,
                'request_item_id' => NULL,
                'product_feature_id' => 51,
                'qty' => 100,
                'unit_price' => '59292',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'id' => 32,
                'quote_id' => 7,
                'request_item_id' => NULL,
                'product_feature_id' => 52,
                'qty' => 100,
                'unit_price' => '59292',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'id' => 33,
                'quote_id' => 7,
                'request_item_id' => NULL,
                'product_feature_id' => 53,
                'qty' => 100,
                'unit_price' => '59292',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'id' => 34,
                'quote_id' => 7,
                'request_item_id' => NULL,
                'product_feature_id' => 54,
                'qty' => 75,
                'unit_price' => '59292',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'id' => 35,
                'quote_id' => 7,
                'request_item_id' => NULL,
                'product_feature_id' => 55,
                'qty' => 50,
                'unit_price' => '59292',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            26 => 
            array (
                'id' => 36,
                'quote_id' => 7,
                'request_item_id' => NULL,
                'product_feature_id' => 56,
                'qty' => 50,
                'unit_price' => '59292',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            27 => 
            array (
                'id' => 37,
                'quote_id' => 7,
                'request_item_id' => NULL,
                'product_feature_id' => 57,
                'qty' => 20,
                'unit_price' => '59292',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            28 => 
            array (
                'id' => 38,
                'quote_id' => 7,
                'request_item_id' => NULL,
                'product_feature_id' => 58,
                'qty' => 20,
                'unit_price' => '59292',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            29 => 
            array (
                'id' => 39,
                'quote_id' => 7,
                'request_item_id' => NULL,
                'product_feature_id' => 59,
                'qty' => 20,
                'unit_price' => '59292',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            30 => 
            array (
                'id' => 40,
                'quote_id' => 7,
                'request_item_id' => NULL,
                'product_feature_id' => 60,
                'qty' => 250,
                'unit_price' => '59292',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            31 => 
            array (
                'id' => 41,
                'quote_id' => 7,
                'request_item_id' => NULL,
                'product_feature_id' => 61,
                'qty' => 100,
                'unit_price' => '59292',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            32 => 
            array (
                'id' => 42,
                'quote_id' => 7,
                'request_item_id' => NULL,
                'product_feature_id' => 62,
                'qty' => 5,
                'unit_price' => '59292',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            33 => 
            array (
                'id' => 43,
                'quote_id' => 7,
                'request_item_id' => NULL,
                'product_feature_id' => 63,
                'qty' => 25,
                'unit_price' => '59292',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            34 => 
            array (
                'id' => 44,
                'quote_id' => 7,
                'request_item_id' => NULL,
                'product_feature_id' => 64,
                'qty' => 30,
                'unit_price' => '59292',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            35 => 
            array (
                'id' => 45,
                'quote_id' => 7,
                'request_item_id' => NULL,
                'product_feature_id' => 65,
                'qty' => 10,
                'unit_price' => '59292',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            36 => 
            array (
                'id' => 46,
                'quote_id' => 7,
                'request_item_id' => NULL,
                'product_feature_id' => 66,
                'qty' => 50,
                'unit_price' => '59292',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            37 => 
            array (
                'id' => 47,
                'quote_id' => 8,
                'request_item_id' => NULL,
                'product_feature_id' => 18,
                'qty' => 61,
                'unit_price' => '23000',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            38 => 
            array (
                'id' => 48,
                'quote_id' => 8,
                'request_item_id' => NULL,
                'product_feature_id' => 19,
                'qty' => 61,
                'unit_price' => '23000',
                'created_at' => NULL,
                'updated_at' => '2022-09-08 13:57:33',
            ),
            39 => 
            array (
                'id' => 49,
                'quote_id' => 8,
                'request_item_id' => NULL,
                'product_feature_id' => 20,
                'qty' => 63,
                'unit_price' => '23000',
                'created_at' => NULL,
                'updated_at' => '2022-09-08 13:57:36',
            ),
            40 => 
            array (
                'id' => 50,
                'quote_id' => 8,
                'request_item_id' => NULL,
                'product_feature_id' => 21,
                'qty' => 66,
                'unit_price' => '23000',
                'created_at' => NULL,
                'updated_at' => '2022-09-08 13:57:41',
            ),
            41 => 
            array (
                'id' => 51,
                'quote_id' => 8,
                'request_item_id' => NULL,
                'product_feature_id' => 22,
                'qty' => 69,
                'unit_price' => '23000',
                'created_at' => NULL,
                'updated_at' => '2022-09-08 13:57:44',
            ),
            42 => 
            array (
                'id' => 52,
                'quote_id' => 8,
                'request_item_id' => NULL,
                'product_feature_id' => 23,
                'qty' => 97,
                'unit_price' => '23000',
                'created_at' => NULL,
                'updated_at' => '2022-09-08 13:57:47',
            ),
            43 => 
            array (
                'id' => 53,
                'quote_id' => 8,
                'request_item_id' => NULL,
                'product_feature_id' => 24,
                'qty' => 91,
                'unit_price' => '23000',
                'created_at' => NULL,
                'updated_at' => '2022-09-08 13:57:52',
            ),
            44 => 
            array (
                'id' => 54,
                'quote_id' => 8,
                'request_item_id' => NULL,
                'product_feature_id' => 25,
                'qty' => 104,
                'unit_price' => '23000',
                'created_at' => NULL,
                'updated_at' => '2022-09-08 13:57:56',
            ),
            45 => 
            array (
                'id' => 55,
                'quote_id' => 8,
                'request_item_id' => NULL,
                'product_feature_id' => 26,
                'qty' => 77,
                'unit_price' => '23000',
                'created_at' => NULL,
                'updated_at' => '2022-09-08 13:57:59',
            ),
            46 => 
            array (
                'id' => 56,
                'quote_id' => 8,
                'request_item_id' => NULL,
                'product_feature_id' => 27,
                'qty' => 79,
                'unit_price' => '23000',
                'created_at' => NULL,
                'updated_at' => '2022-09-08 13:58:03',
            ),
            47 => 
            array (
                'id' => 57,
                'quote_id' => 9,
                'request_item_id' => NULL,
                'product_feature_id' => 28,
                'qty' => 116,
                'unit_price' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            48 => 
            array (
                'id' => 58,
                'quote_id' => 9,
                'request_item_id' => NULL,
                'product_feature_id' => 29,
                'qty' => 87,
                'unit_price' => '0',
                'created_at' => NULL,
                'updated_at' => '2022-09-08 14:01:47',
            ),
            49 => 
            array (
                'id' => 59,
                'quote_id' => 9,
                'request_item_id' => NULL,
                'product_feature_id' => 30,
                'qty' => 87,
                'unit_price' => '0',
                'created_at' => NULL,
                'updated_at' => '2022-09-08 14:02:15',
            ),
            50 => 
            array (
                'id' => 60,
                'quote_id' => 9,
                'request_item_id' => NULL,
                'product_feature_id' => 31,
                'qty' => 232,
                'unit_price' => '0',
                'created_at' => NULL,
                'updated_at' => '2022-09-08 14:01:27',
            ),
            51 => 
            array (
                'id' => 61,
                'quote_id' => 9,
                'request_item_id' => NULL,
                'product_feature_id' => 32,
                'qty' => 174,
                'unit_price' => '0',
                'created_at' => NULL,
                'updated_at' => '2022-09-08 14:01:53',
            ),
            52 => 
            array (
                'id' => 62,
                'quote_id' => 9,
                'request_item_id' => NULL,
                'product_feature_id' => 33,
                'qty' => 174,
                'unit_price' => '0',
                'created_at' => NULL,
                'updated_at' => '2022-09-08 14:02:20',
            ),
            53 => 
            array (
                'id' => 63,
                'quote_id' => 9,
                'request_item_id' => NULL,
                'product_feature_id' => 34,
                'qty' => 232,
                'unit_price' => '0',
                'created_at' => NULL,
                'updated_at' => '2022-09-08 14:01:35',
            ),
            54 => 
            array (
                'id' => 64,
                'quote_id' => 9,
                'request_item_id' => NULL,
                'product_feature_id' => 35,
                'qty' => 174,
                'unit_price' => '0',
                'created_at' => NULL,
                'updated_at' => '2022-09-08 14:02:00',
            ),
            55 => 
            array (
                'id' => 65,
                'quote_id' => 9,
                'request_item_id' => NULL,
                'product_feature_id' => 36,
                'qty' => 174,
                'unit_price' => '0',
                'created_at' => NULL,
                'updated_at' => '2022-09-08 14:02:26',
            ),
            56 => 
            array (
                'id' => 66,
                'quote_id' => 9,
                'request_item_id' => NULL,
                'product_feature_id' => 37,
                'qty' => 116,
                'unit_price' => '0',
                'created_at' => NULL,
                'updated_at' => '2022-09-08 14:01:40',
            ),
            57 => 
            array (
                'id' => 67,
                'quote_id' => 9,
                'request_item_id' => NULL,
                'product_feature_id' => 38,
                'qty' => 87,
                'unit_price' => '0',
                'created_at' => NULL,
                'updated_at' => '2022-09-08 14:02:05',
            ),
            58 => 
            array (
                'id' => 68,
                'quote_id' => 9,
                'request_item_id' => NULL,
                'product_feature_id' => 39,
                'qty' => 87,
                'unit_price' => '0',
                'created_at' => NULL,
                'updated_at' => '2022-09-08 14:02:31',
            ),
            59 => 
            array (
                'id' => 69,
                'quote_id' => 10,
                'request_item_id' => NULL,
                'product_feature_id' => 40,
                'qty' => 77,
                'unit_price' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            60 => 
            array (
                'id' => 70,
                'quote_id' => 10,
                'request_item_id' => NULL,
                'product_feature_id' => 41,
                'qty' => 77,
                'unit_price' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            61 => 
            array (
                'id' => 71,
                'quote_id' => 10,
                'request_item_id' => NULL,
                'product_feature_id' => 42,
                'qty' => 154,
                'unit_price' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            62 => 
            array (
                'id' => 72,
                'quote_id' => 10,
                'request_item_id' => NULL,
                'product_feature_id' => 43,
                'qty' => 154,
                'unit_price' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            63 => 
            array (
                'id' => 73,
                'quote_id' => 10,
                'request_item_id' => NULL,
                'product_feature_id' => 44,
                'qty' => 231,
                'unit_price' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            64 => 
            array (
                'id' => 74,
                'quote_id' => 10,
                'request_item_id' => NULL,
                'product_feature_id' => 45,
                'qty' => 231,
                'unit_price' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            65 => 
            array (
                'id' => 75,
                'quote_id' => 10,
                'request_item_id' => NULL,
                'product_feature_id' => 46,
                'qty' => 309,
                'unit_price' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            66 => 
            array (
                'id' => 76,
                'quote_id' => 10,
                'request_item_id' => NULL,
                'product_feature_id' => 47,
                'qty' => 309,
                'unit_price' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            67 => 
            array (
                'id' => 77,
                'quote_id' => 10,
                'request_item_id' => NULL,
                'product_feature_id' => 48,
                'qty' => 154,
                'unit_price' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            68 => 
            array (
                'id' => 78,
                'quote_id' => 10,
                'request_item_id' => NULL,
                'product_feature_id' => 49,
                'qty' => 154,
                'unit_price' => '0',
                'created_at' => NULL,
                'updated_at' => '2022-09-08 14:05:03',
            ),
            69 => 
            array (
                'id' => 79,
                'quote_id' => 11,
                'request_item_id' => NULL,
                'product_feature_id' => 84,
                'qty' => 100,
                'unit_price' => '29000',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            70 => 
            array (
                'id' => 80,
                'quote_id' => 11,
                'request_item_id' => NULL,
                'product_feature_id' => 85,
                'qty' => 100,
                'unit_price' => '29000',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            71 => 
            array (
                'id' => 81,
                'quote_id' => 11,
                'request_item_id' => NULL,
                'product_feature_id' => 86,
                'qty' => 100,
                'unit_price' => '29000',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            72 => 
            array (
                'id' => 82,
                'quote_id' => 11,
                'request_item_id' => NULL,
                'product_feature_id' => 87,
                'qty' => 100,
                'unit_price' => '29000',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            73 => 
            array (
                'id' => 83,
                'quote_id' => 11,
                'request_item_id' => NULL,
                'product_feature_id' => 88,
                'qty' => 100,
                'unit_price' => '29000',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            74 => 
            array (
                'id' => 84,
                'quote_id' => 11,
                'request_item_id' => NULL,
                'product_feature_id' => 89,
                'qty' => 100,
                'unit_price' => '29000',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            75 => 
            array (
                'id' => 85,
                'quote_id' => 11,
                'request_item_id' => NULL,
                'product_feature_id' => 90,
                'qty' => 100,
                'unit_price' => '29000',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            76 => 
            array (
                'id' => 86,
                'quote_id' => 12,
                'request_item_id' => NULL,
                'product_feature_id' => 91,
                'qty' => 100,
                'unit_price' => '26000',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            77 => 
            array (
                'id' => 87,
                'quote_id' => 12,
                'request_item_id' => NULL,
                'product_feature_id' => 92,
                'qty' => 100,
                'unit_price' => '26000',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            78 => 
            array (
                'id' => 88,
                'quote_id' => 12,
                'request_item_id' => NULL,
                'product_feature_id' => 93,
                'qty' => 100,
                'unit_price' => '26000',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            79 => 
            array (
                'id' => 89,
                'quote_id' => 12,
                'request_item_id' => NULL,
                'product_feature_id' => 94,
                'qty' => 100,
                'unit_price' => '26000',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            80 => 
            array (
                'id' => 90,
                'quote_id' => 12,
                'request_item_id' => NULL,
                'product_feature_id' => 95,
                'qty' => 100,
                'unit_price' => '26000',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            81 => 
            array (
                'id' => 91,
                'quote_id' => 12,
                'request_item_id' => NULL,
                'product_feature_id' => 96,
                'qty' => 100,
                'unit_price' => '26000',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            82 => 
            array (
                'id' => 92,
                'quote_id' => 12,
                'request_item_id' => NULL,
                'product_feature_id' => 97,
                'qty' => 100,
                'unit_price' => '26000',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            83 => 
            array (
                'id' => 93,
                'quote_id' => 12,
                'request_item_id' => NULL,
                'product_feature_id' => 98,
                'qty' => 100,
                'unit_price' => '26000',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            84 => 
            array (
                'id' => 94,
                'quote_id' => 12,
                'request_item_id' => NULL,
                'product_feature_id' => 99,
                'qty' => 100,
                'unit_price' => '26000',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            85 => 
            array (
                'id' => 95,
                'quote_id' => 13,
                'request_item_id' => NULL,
                'product_feature_id' => 121,
                'qty' => 100,
                'unit_price' => '29000',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            86 => 
            array (
                'id' => 96,
                'quote_id' => 13,
                'request_item_id' => NULL,
                'product_feature_id' => 122,
                'qty' => 100,
                'unit_price' => '29000',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            87 => 
            array (
                'id' => 97,
                'quote_id' => 13,
                'request_item_id' => NULL,
                'product_feature_id' => 123,
                'qty' => 100,
                'unit_price' => '29000',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            88 => 
            array (
                'id' => 98,
                'quote_id' => 13,
                'request_item_id' => NULL,
                'product_feature_id' => 124,
                'qty' => 100,
                'unit_price' => '29000',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            89 => 
            array (
                'id' => 99,
                'quote_id' => 14,
                'request_item_id' => NULL,
                'product_feature_id' => 125,
                'qty' => 100,
                'unit_price' => '29000',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            90 => 
            array (
                'id' => 100,
                'quote_id' => 14,
                'request_item_id' => NULL,
                'product_feature_id' => 126,
                'qty' => 100,
                'unit_price' => '29000',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            91 => 
            array (
                'id' => 101,
                'quote_id' => 14,
                'request_item_id' => NULL,
                'product_feature_id' => 127,
                'qty' => 100,
                'unit_price' => '29000',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            92 => 
            array (
                'id' => 102,
                'quote_id' => 14,
                'request_item_id' => NULL,
                'product_feature_id' => 128,
                'qty' => 100,
                'unit_price' => '29000',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            93 => 
            array (
                'id' => 103,
                'quote_id' => 15,
                'request_item_id' => NULL,
                'product_feature_id' => 129,
                'qty' => 100,
                'unit_price' => '29000',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            94 => 
            array (
                'id' => 104,
                'quote_id' => 15,
                'request_item_id' => NULL,
                'product_feature_id' => 130,
                'qty' => 100,
                'unit_price' => '29000',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            95 => 
            array (
                'id' => 105,
                'quote_id' => 15,
                'request_item_id' => NULL,
                'product_feature_id' => 131,
                'qty' => 100,
                'unit_price' => '29000',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            96 => 
            array (
                'id' => 106,
                'quote_id' => 15,
                'request_item_id' => NULL,
                'product_feature_id' => 132,
                'qty' => 100,
                'unit_price' => '29000',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            97 => 
            array (
                'id' => 107,
                'quote_id' => 16,
                'request_item_id' => NULL,
                'product_feature_id' => 133,
                'qty' => 0,
                'unit_price' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            98 => 
            array (
                'id' => 108,
                'quote_id' => 16,
                'request_item_id' => NULL,
                'product_feature_id' => 134,
                'qty' => 0,
                'unit_price' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            99 => 
            array (
                'id' => 109,
                'quote_id' => 16,
                'request_item_id' => NULL,
                'product_feature_id' => 135,
                'qty' => 0,
                'unit_price' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            100 => 
            array (
                'id' => 110,
                'quote_id' => 16,
                'request_item_id' => NULL,
                'product_feature_id' => 136,
                'qty' => 0,
                'unit_price' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            101 => 
            array (
                'id' => 111,
                'quote_id' => 16,
                'request_item_id' => NULL,
                'product_feature_id' => 137,
                'qty' => 0,
                'unit_price' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            102 => 
            array (
                'id' => 112,
                'quote_id' => 16,
                'request_item_id' => NULL,
                'product_feature_id' => 138,
                'qty' => 0,
                'unit_price' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            103 => 
            array (
                'id' => 113,
                'quote_id' => 16,
                'request_item_id' => NULL,
                'product_feature_id' => 139,
                'qty' => 0,
                'unit_price' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            104 => 
            array (
                'id' => 114,
                'quote_id' => 16,
                'request_item_id' => NULL,
                'product_feature_id' => 140,
                'qty' => 0,
                'unit_price' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            105 => 
            array (
                'id' => 115,
                'quote_id' => 16,
                'request_item_id' => NULL,
                'product_feature_id' => 141,
                'qty' => 0,
                'unit_price' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            106 => 
            array (
                'id' => 116,
                'quote_id' => 16,
                'request_item_id' => NULL,
                'product_feature_id' => 142,
                'qty' => 0,
                'unit_price' => '0',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            107 => 
            array (
                'id' => 117,
                'quote_id' => 17,
                'request_item_id' => NULL,
                'product_feature_id' => 165,
                'qty' => 4611,
                'unit_price' => '44800',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            108 => 
            array (
                'id' => 118,
                'quote_id' => 17,
                'request_item_id' => NULL,
                'product_feature_id' => 166,
                'qty' => 4611,
                'unit_price' => '44800',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            109 => 
            array (
                'id' => 119,
                'quote_id' => 17,
                'request_item_id' => NULL,
                'product_feature_id' => 167,
                'qty' => 4611,
                'unit_price' => '44800',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            110 => 
            array (
                'id' => 120,
                'quote_id' => 18,
                'request_item_id' => NULL,
                'product_feature_id' => 168,
                'qty' => 20,
                'unit_price' => '19820',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            111 => 
            array (
                'id' => 121,
                'quote_id' => 18,
                'request_item_id' => NULL,
                'product_feature_id' => 169,
                'qty' => 107,
                'unit_price' => '44145',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            112 => 
            array (
                'id' => 122,
                'quote_id' => 19,
                'request_item_id' => NULL,
                'product_feature_id' => 182,
                'qty' => 100,
                'unit_price' => '30000',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            113 => 
            array (
                'id' => 123,
                'quote_id' => 19,
                'request_item_id' => NULL,
                'product_feature_id' => 183,
                'qty' => 100,
                'unit_price' => '30000',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            114 => 
            array (
                'id' => 124,
                'quote_id' => 19,
                'request_item_id' => NULL,
                'product_feature_id' => 184,
                'qty' => 100,
                'unit_price' => '30000',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            115 => 
            array (
                'id' => 125,
                'quote_id' => 19,
                'request_item_id' => NULL,
                'product_feature_id' => 185,
                'qty' => 100,
                'unit_price' => '30000',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}