<?php

use Illuminate\Database\Seeder;

class WorkCenterTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('work_center')->delete();
        
        \DB::table('work_center')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Sewing Line',
                'company_name' => 'PT. BSI',
                'oee_target' => 90,
                'prod_capacity' => 1000,
                'work_hours' => 5,
                'layout_produksi' => 0,
                'cost_per_hour' => 8500000,
                'labor_alloc' => 30,
                'description' => 'Sewing',
                'overhead_cost' => 0,
                'created_at' => '2022-09-03 16:51:52',
                'updated_at' => '2022-09-03 16:51:52',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Sewing Line 1',
                'company_name' => 'PT BSI Indonesia',
                'oee_target' => 1,
                'prod_capacity' => 30,
                'work_hours' => 10,
                'layout_produksi' => 0,
                'cost_per_hour' => 8500000,
                'labor_alloc' => 30,
                'description' => 'haahah',
                'overhead_cost' => 30000,
                'created_at' => '2022-09-08 03:26:31',
                'updated_at' => '2022-09-08 03:26:31',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'BIENSI-STYLE6-LINE',
                'company_name' => 'PT. Buana Sandang Indonesia',
                'oee_target' => 1,
                'prod_capacity' => 400,
                'work_hours' => 8,
                'layout_produksi' => 0,
                'cost_per_hour' => 10000000,
                'labor_alloc' => 40,
                'description' => 'BIENSI',
                'overhead_cost' => 0,
                'created_at' => '2022-09-21 11:45:58',
                'updated_at' => '2022-09-21 11:45:58',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'BIENSI-STYLE3-LINE',
                'company_name' => 'PT Buana Sandang Indonesia',
                'oee_target' => 1,
                'prod_capacity' => 400,
                'work_hours' => 28,
                'layout_produksi' => 3,
                'cost_per_hour' => 10000000,
                'labor_alloc' => 40,
                'description' => 'Sewing',
                'overhead_cost' => 0,
                'created_at' => '2022-09-27 01:13:10',
                'updated_at' => '2022-09-27 01:13:10',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'Cressida-Line1',
                'company_name' => 'PT Buana Sandang Indonesia',
                'oee_target' => 3,
                'prod_capacity' => 840,
                'work_hours' => 26,
                'layout_produksi' => 1,
                'cost_per_hour' => 10000000,
                'labor_alloc' => 35,
                'description' => 'Cressida',
                'overhead_cost' => 0,
                'created_at' => '2022-10-05 02:18:54',
                'updated_at' => '2022-10-05 02:18:54',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'KKS Emba-DEVANO,EDDIE,DAREN',
                'company_name' => 'PT Buana Sandang Indonesia',
                'oee_target' => 1,
                'prod_capacity' => 280,
                'work_hours' => 15,
                'layout_produksi' => 3,
                'cost_per_hour' => 0,
                'labor_alloc' => 40,
                'description' => 'Emba Sewing Line',
                'overhead_cost' => 0,
                'created_at' => '2022-10-05 03:20:41',
                'updated_at' => '2022-10-05 03:20:41',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'KKS Emba-DEVANO',
                'company_name' => 'PT Buana Sandang Indonesia',
                'oee_target' => 1,
                'prod_capacity' => 280,
                'work_hours' => 4,
                'layout_produksi' => 0,
                'cost_per_hour' => 10000000,
                'labor_alloc' => 40,
                'description' => 'Emba Sewing Line',
                'overhead_cost' => 0,
                'created_at' => '2022-10-05 03:21:32',
                'updated_at' => '2022-10-05 03:26:15',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'KKS Emba-EDDIE',
                'company_name' => 'PT Buana Sandang Indonesia',
                'oee_target' => 1,
                'prod_capacity' => 280,
                'work_hours' => 6,
                'layout_produksi' => 1,
                'cost_per_hour' => 10000000,
                'labor_alloc' => 40,
                'description' => 'Emba Sewing Line',
                'overhead_cost' => 0,
                'created_at' => '2022-10-05 03:21:52',
                'updated_at' => '2022-10-05 03:21:52',
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'KKS Emba-DAREN',
                'company_name' => 'PT Buana Sandang Indonesia',
                'oee_target' => 1,
                'prod_capacity' => 280,
                'work_hours' => 4,
                'layout_produksi' => 1,
                'cost_per_hour' => 10000000,
                'labor_alloc' => 40,
                'description' => 'Emba Sewing Line',
                'overhead_cost' => 0,
                'created_at' => '2022-10-05 03:22:10',
                'updated_at' => '2022-10-05 03:22:10',
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Sewing-Line-Menshirt',
                'company_name' => 'PT Buana Sandang Indonesia',
                'oee_target' => 3,
                'prod_capacity' => 500,
                'work_hours' => 8,
                'layout_produksi' => 2,
                'cost_per_hour' => 10000000,
                'labor_alloc' => 25,
                'description' => 'Sewing',
                'overhead_cost' => 0,
                'created_at' => '2022-10-13 03:11:27',
                'updated_at' => '2022-10-13 03:11:27',
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'SEWING_KKS_EMBA_SPIRNGBOXANDTOMSKY',
                'company_name' => 'PT Buana Sandang Indoensia',
                'oee_target' => 1,
                'prod_capacity' => 700,
                'work_hours' => 26,
                'layout_produksi' => 0,
                'cost_per_hour' => 20000000,
                'labor_alloc' => 70,
                'description' => 'Karna layout sudah dilakukan sebelumnya',
                'overhead_cost' => 0,
                'created_at' => '2022-10-14 00:19:42',
                'updated_at' => '2022-10-14 00:25:57',
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'Jacket Pegasus',
                'company_name' => 'PT Kasih Karunia Sejati',
                'oee_target' => 1,
                'prod_capacity' => 400,
                'work_hours' => 5,
                'layout_produksi' => 2,
                'cost_per_hour' => 10000000,
                'labor_alloc' => 40,
                'description' => 'Done',
                'overhead_cost' => 0,
                'created_at' => '2022-10-14 02:51:45',
                'updated_at' => '2022-10-19 06:22:52',
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'Jacket Winslow dan Pegasus',
                'company_name' => 'PT Buana Sandang Indonesia',
                'oee_target' => 1,
                'prod_capacity' => 300,
                'work_hours' => 7,
                'layout_produksi' => 2,
                'cost_per_hour' => 10000000,
                'labor_alloc' => 40,
                'description' => 'Done',
                'overhead_cost' => 0,
                'created_at' => '2022-10-14 02:56:36',
                'updated_at' => '2022-10-19 06:44:13',
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'Eagle Pants',
                'company_name' => 'PT Buana Sandang Indonesia',
                'oee_target' => 1,
                'prod_capacity' => 400,
                'work_hours' => 0,
                'layout_produksi' => 0,
                'cost_per_hour' => 10000000,
                'labor_alloc' => 40,
                'description' => 'Untuk rencana qty produksi yg akan turun belum tau',
                'overhead_cost' => 0,
                'created_at' => '2022-10-14 02:58:25',
                'updated_at' => '2022-10-14 02:58:25',
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'Gates',
                'company_name' => 'PT Buana Sandang Indonesia',
                'oee_target' => 1,
                'prod_capacity' => 250,
                'work_hours' => 8,
                'layout_produksi' => 2,
                'cost_per_hour' => 10000000,
                'labor_alloc' => 40,
                'description' => 'Done',
                'overhead_cost' => 0,
                'created_at' => '2022-10-14 02:59:47',
                'updated_at' => '2022-10-19 06:23:22',
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'Finley, Eagle, dan Gates Pants',
                'company_name' => 'PT Buana Sandang Indonesia',
                'oee_target' => 1,
                'prod_capacity' => 300,
                'work_hours' => 19,
                'layout_produksi' => 2,
                'cost_per_hour' => 10000000,
                'labor_alloc' => 40,
                'description' => 'Done',
                'overhead_cost' => 0,
                'created_at' => '2022-10-14 03:01:25',
                'updated_at' => '2022-10-19 06:26:12',
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'Kemeja Deon Two',
                'company_name' => 'PT Buana Sandang Indonesia',
                'oee_target' => 2,
                'prod_capacity' => 500,
                'work_hours' => 0,
                'layout_produksi' => 0,
                'cost_per_hour' => 10000000,
                'labor_alloc' => 40,
                'description' => 'Untuk rencana qty produksi yg akan turun belum tau
Permintaan harga dari BSI Rp 25.000',
                'overhead_cost' => 0,
                'created_at' => '2022-10-14 03:08:55',
                'updated_at' => '2022-10-14 03:08:55',
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'Kemeja 6388 - BBI Jakarta',
                'company_name' => 'PT Buana Sandang Indonesia',
                'oee_target' => 1,
                'prod_capacity' => 400,
                'work_hours' => 0,
                'layout_produksi' => 0,
                'cost_per_hour' => 10000000,
                'labor_alloc' => 40,
                'description' => 'Untuk rencana qty produksi yg akan turun belum tau
Permintaan harga dari BSI Rp 30.000',
                'overhead_cost' => 0,
                'created_at' => '2022-10-14 03:11:05',
                'updated_at' => '2022-10-14 03:11:05',
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'BIENSI_TOMTAYLOR_NOV',
                'company_name' => 'PT Buana Sandang Indonesia',
                'oee_target' => 2,
                'prod_capacity' => 400,
                'work_hours' => 8,
                'layout_produksi' => 0,
                'cost_per_hour' => 10000000,
                'labor_alloc' => 35,
                'description' => 'Done',
                'overhead_cost' => 0,
                'created_at' => '2022-10-14 05:59:39',
                'updated_at' => '2022-10-29 02:52:50',
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'AOI T785, T797, T796, S169, T819',
                'company_name' => 'PT Buana Sandang Indonesia',
                'oee_target' => 1,
                'prod_capacity' => 280,
                'work_hours' => 9,
                'layout_produksi' => 0,
                'cost_per_hour' => 10000000,
                'labor_alloc' => 40,
                'description' => 'DONE',
                'overhead_cost' => 0,
                'created_at' => '2022-10-18 03:59:49',
                'updated_at' => '2022-10-18 05:06:18',
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'II_AOI T785, T797, T796, S169, T819',
                'company_name' => 'PT Buana Sandang Indonesia',
                'oee_target' => 0,
                'prod_capacity' => 150,
                'work_hours' => 15,
                'layout_produksi' => 0,
                'cost_per_hour' => 10000000,
                'labor_alloc' => 40,
                'description' => 'Done',
                'overhead_cost' => 0,
                'created_at' => '2022-10-18 05:11:21',
                'updated_at' => '2022-10-18 05:13:21',
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'I_ISG_Celana_Okt_2022',
                'company_name' => 'PT. Buana Sandang Indonesia',
                'oee_target' => 2,
                'prod_capacity' => 500,
                'work_hours' => 12,
                'layout_produksi' => 2,
                'cost_per_hour' => 10000000,
                'labor_alloc' => 40,
                'description' => 'done',
                'overhead_cost' => 0,
                'created_at' => '2022-10-18 08:43:24',
                'updated_at' => '2022-10-18 08:43:24',
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'II_ISG_Celana_Okt_2022',
                'company_name' => 'PT Buana Sandang Indonesia',
                'oee_target' => 1,
                'prod_capacity' => 400,
                'work_hours' => 14,
                'layout_produksi' => 2,
                'cost_per_hour' => 10000000,
                'labor_alloc' => 40,
                'description' => 'Done',
                'overhead_cost' => 0,
                'created_at' => '2022-10-19 04:53:08',
                'updated_at' => '2022-10-19 04:53:08',
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'III_ISG_Celana_Okt_2022',
                'company_name' => 'PT Buana Sandang Indonesia',
                'oee_target' => 1,
                'prod_capacity' => 350,
                'work_hours' => 16,
                'layout_produksi' => 2,
                'cost_per_hour' => 10000000,
                'labor_alloc' => 40,
                'description' => 'Done',
                'overhead_cost' => 0,
                'created_at' => '2022-10-19 04:54:14',
                'updated_at' => '2022-10-19 04:54:14',
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'ISG-JOEYRIDAPANTS-SEWING',
                'company_name' => 'PT. Buana Sandang Indonesia',
                'oee_target' => 2,
                'prod_capacity' => 600,
                'work_hours' => 17,
                'layout_produksi' => 0,
                'cost_per_hour' => 10000000,
                'labor_alloc' => 40,
                'description' => 'Done',
                'overhead_cost' => 0,
                'created_at' => '2022-10-26 07:12:58',
                'updated_at' => '2022-10-26 07:14:06',
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'ISG-JOEYRIDAPANTS-SEWING',
                'company_name' => 'PT. Buana Sandang Indonesia',
                'oee_target' => 2,
                'prod_capacity' => 600,
                'work_hours' => 17,
                'layout_produksi' => 3,
                'cost_per_hour' => 12500000,
                'labor_alloc' => 40,
                'description' => 'Done',
                'overhead_cost' => 0,
                'created_at' => '2022-10-26 07:13:22',
                'updated_at' => '2022-10-26 07:13:22',
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'ISG-JOEYRIDAPANTS-SEWING-500',
                'company_name' => 'PT Buana Sandang Indonesia',
                'oee_target' => 2,
                'prod_capacity' => 480,
                'work_hours' => 19,
                'layout_produksi' => 0,
                'cost_per_hour' => 11000000,
                'labor_alloc' => 40,
                'description' => 'DONE',
                'overhead_cost' => 0,
                'created_at' => '2022-10-26 07:19:42',
                'updated_at' => '2022-10-26 07:22:12',
            ),
        ));
        
        
    }
}