[
  {
    "Jenis Dokumen Kepabeanan": "BC 2.0",
    "Nomor Pendaftaran Dokumen Pabean": "12345678",
    "Tanggal Dokumen Kepabeanan": "2023-06-01",
    "Nomor Seri Barang": "ABC123",
    "Nomor Bukti Penerimaan Barang": "PR-001",
    "Tanggal Bukti Penerimaan Barang": "2023-06-03",
    "Kode Barang": "123456",
    "Nama Barang": "Widget A",
    "Satuan Barang": "Piece",
    "Jumlah Barang": 100,
    "Mata Uang": "USD",
    "Nilai Barang": 5000,
    "Nama Penerima Subkontrak": "Subkon A",
    "Perusahaan Pengirim atau Negara Asal Barang": "USA"
  },
  {
    "Jenis Dokumen Kepabeanan": "BC 2.4",
    "Nomor Pendaftaran Dokumen Pabean": "87654321",
    "Tanggal Dokumen Kepabeanan": "2023-06-05",
    "Nomor Seri Barang": "DEF456",
    "Nomor Bukti Penerimaan Barang": "PR-002",
    "Tanggal Bukti Penerimaan Barang": "2023-06-06",
    "Kode Barang": "789012",
    "Nama Barang": "Widget B",
    "Satuan Barang": "Box",
    "Jumlah Barang": 50,
    "Mata Uang": "EUR",
    "Nilai Barang": 2500,
    "Nama Penerima Subkontrak": "Subkon B",
    "Perusahaan Pengirim atau Negara Asal Barang": "Germany"
  },
  {
    "Jenis Dokumen Kepabeanan": "BC 2.5",
    "Nomor Pendaftaran Dokumen Pabean": "65432198",
    "Tanggal Dokumen Kepabeanan": "2023-06-10",
    "Nomor Seri Barang": "XYZ789",
    "Nomor Bukti Penerimaan Barang": "PR-003",
    "Tanggal Bukti Penerimaan Barang": "2023-06-12",
    "Kode Barang": "345678",
    "Nama Barang": "Widget C",
    "Satuan Barang": "Set",
    "Jumlah Barang": 20,
    "Mata Uang": "JPY",
    "Nilai Barang": 10000,
    "Nama Penerima Subkontrak": "Subkon C",
    "Perusahaan Pengirim atau Negara Asal Barang": "Japan"
  },
  {
    "Jenis Dokumen Kepabeanan": "BC 2.8",
    "Nomor Pendaftaran Dokumen Pabean": "98765432",
    "Tanggal Dokumen Kepabeanan": "2023-06-15",
    "Nomor Seri Barang": "LMN012",
    "Nomor Bukti Penerimaan Barang": "PR-004",
    "Tanggal Bukti Penerimaan Barang": "2023-06-17",
    "Kode Barang": "901234",
    "Nama Barang": "Widget D",
    "Satuan Barang": "Piece",
    "Jumlah Barang": 200,
    "Mata Uang": "CAD",
    "Nilai Barang": 8000,
    "Nama Penerima Subkontrak": "Subkon D",
    "Perusahaan Pengirim atau Negara Asal Barang": "Canada"
  },
  {
    "Jenis Dokumen Kepabeanan": "BC 2.0",
    "Nomor Pendaftaran Dokumen Pabean": "23456789",
    "Tanggal Dokumen Kepabeanan": "2023-06-02",
    "Nomor Seri Barang": "PQR345",
    "Nomor Bukti Penerimaan Barang": "PR-005",
    "Tanggal Bukti Penerimaan Barang": "2023-06-04",
    "Kode Barang": "567890",
    "Nama Barang": "Widget E",
    "Satuan Barang": "Piece",
    "Jumlah Barang": 150,
    "Mata Uang": "GBP",
    "Nilai Barang": 6000,
    "Nama Penerima Subkontrak": "Subkon E",
    "Perusahaan Pengirim atau Negara Asal Barang": "UK"
  },
  {
    "Jenis Dokumen Kepabeanan": "BC 2.0",
    "Nomor Pendaftaran Dokumen Pabean": "98765432",
    "Tanggal Dokumen Kepabeanan": "2023-06-10",
    "Nomor Seri Barang": "LMN987",
    "Nomor Bukti Penerimaan Barang": "PR-006",
    "Tanggal Bukti Penerimaan Barang": "2023-06-12",
    "Kode Barang": "890123",
    "Nama Barang": "Widget F",
    "Satuan Barang": "Piece",
    "Jumlah Barang": 80,
    "Mata Uang": "USD",
    "Nilai Barang": 4000,
    "Nama Penerima Subkontrak": "Subkon F",
    "Perusahaan Pengirim atau Negara Asal Barang": "USA"
  },
  {
    "Jenis Dokumen Kepabeanan": "BC 2.4",
    "Nomor Pendaftaran Dokumen Pabean": "76543210",
    "Tanggal Dokumen Kepabeanan": "2023-06-07",
    "Nomor Seri Barang": "MNO789",
    "Nomor Bukti Penerimaan Barang": "PR-007",
    "Tanggal Bukti Penerimaan Barang": "2023-06-09",
    "Kode Barang": "098765",
    "Nama Barang": "Widget G",
    "Satuan Barang": "Box",
    "Jumlah Barang": 40,
    "Mata Uang": "EUR",
    "Nilai Barang": 2000,
    "Nama Penerima Subkontrak": "Subkon G",
    "Perusahaan Pengirim atau Negara Asal Barang": "Germany"
  },
  {
    "Jenis Dokumen Kepabeanan": "BC 2.5",
    "Nomor Pendaftaran Dokumen Pabean": "54321678",
    "Tanggal Dokumen Kepabeanan": "2023-06-12",
    "Nomor Seri Barang": "QRS123",
    "Nomor Bukti Penerimaan Barang": "PR-008",
    "Tanggal Bukti Penerimaan Barang": "2023-06-14",
    "Kode Barang": "234567",
    "Nama Barang": "Widget H",
    "Satuan Barang": "Set",
    "Jumlah Barang": 30,
    "Mata Uang": "JPY",
    "Nilai Barang": 15000,
    "Nama Penerima Subkontrak": "Subkon H",
    "Perusahaan Pengirim atau Negara Asal Barang": "Japan"
  },
  {
    "Jenis Dokumen Kepabeanan": "BC 2.8",
    "Nomor Pendaftaran Dokumen Pabean": "87654321",
    "Tanggal Dokumen Kepabeanan": "2023-06-17",
    "Nomor Seri Barang": "XYZ789",
    "Nomor Bukti Penerimaan Barang": "PR-009",
    "Tanggal Bukti Penerimaan Barang": "2023-06-19",
    "Kode Barang": "345678",
    "Nama Barang": "Widget I",
    "Satuan Barang": "Piece",
    "Jumlah Barang": 120,
    "Mata Uang": "CAD",
    "Nilai Barang": 4800,
    "Nama Penerima Subkontrak": "Subkon I",
    "Perusahaan Pengirim atau Negara Asal Barang": "Canada"
  },
  {
    "Jenis Dokumen Kepabeanan": "BC 2.0",
    "Nomor Pendaftaran Dokumen Pabean": "76543210",
    "Tanggal Dokumen Kepabeanan": "2023-06-03",
    "Nomor Seri Barang": "LMN012",
    "Nomor Bukti Penerimaan Barang": "PR-010",
    "Tanggal Bukti Penerimaan Barang": "2023-06-05",
    "Kode Barang": "901234",
    "Nama Barang": "Widget J",
    "Satuan Barang": "Piece",
    "Jumlah Barang": 90,
    "Mata Uang": "GBP",
    "Nilai Barang": 3600,
    "Nama Penerima Subkontrak": "Subkon J",
    "Perusahaan Pengirim atau Negara Asal Barang": "UK"
  }
]
