export const __payload = [
  {
    "tanggal_dokumen_cukai_keluar": "2023-01-01",
    "jenis_dokumen": "BC 2.0",
    "nomor_surat_cukai": "CK001",
    "nomor_seri_barang": "NSB001",
    "po_date": "2022-12-15",
    "nomor_purchase_order": "PO001",
    "sku_barang": "SKU001",
    "item_name": "Item A",
    "category": "Category A",
    "qty": 10,
    "unit_measurement": "Pcs",
    "unit_price": 5,
    "country": "USA"
  },
  {
    "tanggal_dokumen_cukai_keluar": "2023-01-02",
    "jenis_dokumen": "BC 2.4",
    "nomor_surat_cukai": "CK002",
    "nomor_seri_barang": "NSB002",
    "po_date": "2022-12-16",
    "nomor_purchase_order": "PO002",
    "sku_barang": "SKU002",
    "item_name": "Item B",
    "category": "Category B",
    "qty": 15,
    "unit_measurement": "Kg",
    "unit_price": 3,
    "country": "China"
  },
  {
    "tanggal_dokumen_cukai_keluar": "2023-01-03",
    "jenis_dokumen": "BC 3.0",
    "nomor_surat_cukai": "CK003",
    "nomor_seri_barang": "NSB003",
    "po_date": "2022-12-17",
    "nomor_purchase_order": "PO003",
    "sku_barang": "SKU003",
    "item_name": "Item C",
    "category": "Category A",
    "qty": 20,
    "unit_measurement": "Pcs",
    "unit_price": 7,
    "country": "USA"
  },
  {
    "tanggal_dokumen_cukai_keluar": "2023-01-04",
    "jenis_dokumen": "BC 2.4",
    "nomor_surat_cukai": "CK004",
    "nomor_seri_barang": "NSB004",
    "po_date": "2022-12-18",
    "nomor_purchase_order": "PO004",
    "sku_barang": "SKU004",
    "item_name": "Item D",
    "category": "Category C",
    "qty": 5,
    "unit_measurement": "Meter",
    "unit_price": 10,
    "country": "Germany"
  },
  {
    "tanggal_dokumen_cukai_keluar": "2023-01-05",
    "jenis_dokumen": "BC 2.0",
    "nomor_surat_cukai": "CK005",
    "nomor_seri_barang": "NSB005",
    "po_date": "2022-12-19",
    "nomor_purchase_order": "PO005",
    "sku_barang": "SKU005",
    "item_name": "Item E",
    "category": "Category B",
    "qty": 12,
    "unit_measurement": "Kg",
    "unit_price": 8,
    "country": "China"
  },
  {
    "tanggal_dokumen_cukai_keluar": "2023-01-06",
    "jenis_dokumen": "BC 2.0",
    "nomor_surat_cukai": "CK006",
    "nomor_seri_barang": "NSB006",
    "po_date": "2022-12-20",
    "nomor_purchase_order": "PO006",
    "sku_barang": "SKU006",
    "item_name": "Item F",
    "category": "Category A",
    "qty": 8,
    "unit_measurement": "Pcs",
    "unit_price": 6,
    "country": "USA"
  },
  {
    "tanggal_dokumen_cukai_keluar": "2023-01-07",
    "jenis_dokumen": "BC 2.4",
    "nomor_surat_cukai": "CK007",
    "nomor_seri_barang": "NSB007",
    "po_date": "2022-12-21",
    "nomor_purchase_order": "PO007",
    "sku_barang": "SKU007",
    "item_name": "Item G",
    "category": "Category C",
    "qty": 15,
    "unit_measurement": "Meter",
    "unit_price": 12,
    "country": "Germany"
  },
  {
    "tanggal_dokumen_cukai_keluar": "2023-01-08",
    "jenis_dokumen": "BC 2.0",
    "nomor_surat_cukai": "CK008",
    "nomor_seri_barang": "NSB008",
    "po_date": "2022-12-22",
    "nomor_purchase_order": "PO008",
    "sku_barang": "SKU008",
    "item_name": "Item H",
    "category": "Category A",
    "qty": 6,
    "unit_measurement": "Pcs",
    "unit_price": 9,
    "country": "USA"
  },
  {
    "tanggal_dokumen_cukai_keluar": "2023-01-09",
    "jenis_dokumen": "BC 3.0",
    "nomor_surat_cukai": "CK009",
    "nomor_seri_barang": "NSB009",
    "po_date": "2022-12-23",
    "nomor_purchase_order": "PO009",
    "sku_barang": "SKU009",
    "item_name": "Item I",
    "category": "Category B",
    "qty": 10,
    "unit_measurement": "Kg",
    "unit_price": 7,
    "country": "China"
  },
  {
    "tanggal_dokumen_cukai_keluar": "2023-01-10",
    "jenis_dokumen": "BC 2.4",
    "nomor_surat_cukai": "CK010",
    "nomor_seri_barang": "NSB010",
    "po_date": "2022-12-24",
    "nomor_purchase_order": "PO010",
    "sku_barang": "SKU010",
    "item_name": "Item J",
    "category": "Category C",
    "qty": 18,
    "unit_measurement": "Meter",
    "unit_price": 5,
    "country": "Germany"
  },
  {
    "tanggal_dokumen_cukai_keluar": "2023-01-11",
    "jenis_dokumen": "BC 3.0",
    "nomor_surat_cukai": "CK011",
    "nomor_seri_barang": "NSB011",
    "po_date": "2022-12-25",
    "nomor_purchase_order": "PO011",
    "sku_barang": "SKU011",
    "item_name": "Item K",
    "category": "Category A",
    "qty": 13,
    "unit_measurement": "Pcs",
    "unit_price": 4,
    "country": "USA"
  },
  {
    "tanggal_dokumen_cukai_keluar": "2023-01-12",
    "jenis_dokumen": "BC 3.0",
    "nomor_surat_cukai": "CK012",
    "nomor_seri_barang": "NSB012",
    "po_date": "2022-12-26",
    "nomor_purchase_order": "PO012",
    "sku_barang": "SKU012",
    "item_name": "Item L",
    "category": "Category B",
    "qty": 7,
    "unit_measurement": "Kg",
    "unit_price": 6,
    "country": "China"
  },
  {
    "tanggal_dokumen_cukai_keluar": "2023-01-13",
    "jenis_dokumen": "BC 2.4",
    "nomor_surat_cukai": "CK013",
    "nomor_seri_barang": "NSB013",
    "po_date": "2022-12-27",
    "nomor_purchase_order": "PO013",
    "sku_barang": "SKU013",
    "item_name": "Item M",
    "category": "Category A",
    "qty": 10,
    "unit_measurement": "Pcs",
    "unit_price": 3,
    "country": "USA"
  },
  {
    "tanggal_dokumen_cukai_keluar": "2023-01-14",
    "jenis_dokumen": "BC 2.4",
    "nomor_surat_cukai": "CK014",
    "nomor_seri_barang": "NSB014",
    "po_date": "2022-12-28",
    "nomor_purchase_order": "PO014",
    "sku_barang": "SKU014",
    "item_name": "Item N",
    "category": "Category C",
    "qty": 16,
    "unit_measurement": "Meter",
    "unit_price": 8,
    "country": "Germany"
  },
  {
    "tanggal_dokumen_cukai_keluar": "2023-01-15",
    "jenis_dokumen": "BC 3.0",
    "nomor_surat_cukai": "CK015",
    "nomor_seri_barang": "NSB015",
    "po_date": "2022-12-29",
    "nomor_purchase_order": "PO015",
    "sku_barang": "SKU015",
    "item_name": "Item O",
    "category": "Category B",
    "qty": 9,
    "unit_measurement": "Kg",
    "unit_price": 5,
    "country": "China"
  },
  {
    "tanggal_dokumen_cukai_keluar": "2023-01-16",
    "jenis_dokumen": "BC 3.0",
    "nomor_surat_cukai": "CK016",
    "nomor_seri_barang": "NSB016",
    "po_date": "2022-12-30",
    "nomor_purchase_order": "PO016",
    "sku_barang": "SKU016",
    "item_name": "Item P",
    "category": "Category A",
    "qty": 11,
    "unit_measurement": "Pcs",
    "unit_price": 4,
    "country": "USA"
  },
  {
    "tanggal_dokumen_cukai_keluar": "2023-01-17",
    "jenis_dokumen": "BC 2.0",
    "nomor_surat_cukai": "CK017",
    "nomor_seri_barang": "NSB017",
    "po_date": "2022-12-31",
    "nomor_purchase_order": "PO017",
    "sku_barang": "SKU017",
    "item_name": "Item Q",
    "category": "Category B",
    "qty": 13,
    "unit_measurement": "Kg",
    "unit_price": 6,
    "country": "China"
  },
  {
    "tanggal_dokumen_cukai_keluar": "2023-01-18",
    "jenis_dokumen": "BC 2.0",
    "nomor_surat_cukai": "CK018",
    "nomor_seri_barang": "NSB018",
    "po_date": "2023-01-01",
    "nomor_purchase_order": "PO018",
    "sku_barang": "SKU018",
    "item_name": "Item R",
    "category": "Category C",
    "qty": 14,
    "unit_measurement": "Meter",
    "unit_price": 9,
    "country": "Germany"
  },
  {
    "tanggal_dokumen_cukai_keluar": "2023-01-19",
    "jenis_dokumen": "BC 2.4",
    "nomor_surat_cukai": "CK019",
    "nomor_seri_barang": "NSB019",
    "po_date": "2023-01-02",
    "nomor_purchase_order": "PO019",
    "sku_barang": "SKU019",
    "item_name": "Item S",
    "category": "Category A",
    "qty": 7,
    "unit_measurement": "Pcs",
    "unit_price": 5,
    "country": "USA"
  },
  {
    "tanggal_dokumen_cukai_keluar": "2023-01-20",
    "jenis_dokumen": "BC 3.0",
    "nomor_surat_cukai": "CK020",
    "nomor_seri_barang": "NSB020",
    "po_date": "2023-01-03",
    "nomor_purchase_order": "PO020",
    "sku_barang": "SKU020",
    "item_name": "Item T",
    "category": "Category B",
    "qty": 9,
    "unit_measurement": "Kg",
    "unit_price": 7,
    "country": "China"
  },
  {
    "tanggal_dokumen_cukai_keluar": "2023-01-21",
    "jenis_dokumen": "BC 2.4",
    "nomor_surat_cukai": "CK021",
    "nomor_seri_barang": "NSB021",
    "po_date": "2023-01-04",
    "nomor_purchase_order": "PO021",
    "sku_barang": "SKU021",
    "item_name": "Item U",
    "category": "Category C",
    "qty": 11,
    "unit_measurement": "Meter",
    "unit_price": 6,
    "country": "Germany"
  },
  {
    "tanggal_dokumen_cukai_keluar": "2023-01-22",
    "jenis_dokumen": "BC 2.0",
    "nomor_surat_cukai": "CK022",
    "nomor_seri_barang": "NSB022",
    "po_date": "2023-01-05",
    "nomor_purchase_order": "PO022",
    "sku_barang": "SKU022",
    "item_name": "Item V",
    "category": "Category A",
    "qty": 12,
    "unit_measurement": "Pcs",
    "unit_price": 8,
    "country": "USA"
  },
  {
    "tanggal_dokumen_cukai_keluar": "2023-01-23",
    "jenis_dokumen": "BC 2.0",
    "nomor_surat_cukai": "CK023",
    "nomor_seri_barang": "NSB023",
    "po_date": "2023-01-06",
    "nomor_purchase_order": "PO023",
    "sku_barang": "SKU023",
    "item_name": "Item W",
    "category": "Category B",
    "qty": 8,
    "unit_measurement": "Kg",
    "unit_price": 6,
    "country": "China"
  },
  {
    "tanggal_dokumen_cukai_keluar": "2023-01-24",
    "jenis_dokumen": "BC 2.4",
    "nomor_surat_cukai": "CK024",
    "nomor_seri_barang": "NSB024",
    "po_date": "2023-01-07",
    "nomor_purchase_order": "PO024",
    "sku_barang": "SKU024",
    "item_name": "Item X",
    "category": "Category A",
    "qty": 10,
    "unit_measurement": "Pcs",
    "unit_price": 5,
    "country": "USA"
  },
  {
    "tanggal_dokumen_cukai_keluar": "2023-01-25",
    "jenis_dokumen": "BC 2.0",
    "nomor_surat_cukai": "CK025",
    "nomor_seri_barang": "NSB025",
    "po_date": "2023-01-08",
    "nomor_purchase_order": "PO025",
    "sku_barang": "SKU025",
    "item_name": "Item Y",
    "category": "Category C",
    "qty": 9,
    "unit_measurement": "Meter",
    "unit_price": 7,
    "country": "Germany"
  },
  {
    "tanggal_dokumen_cukai_keluar": "2023-01-26",
    "jenis_dokumen": "BC 2.0",
    "nomor_surat_cukai": "CK026",
    "nomor_seri_barang": "NSB026",
    "po_date": "2023-01-09",
    "nomor_purchase_order": "PO026",
    "sku_barang": "SKU026",
    "item_name": "Item Z",
    "category": "Category B",
    "qty": 15,
    "unit_measurement": "Kg",
    "unit_price": 4,
    "country": "China"
  },
  {
    "tanggal_dokumen_cukai_keluar": "2023-01-27",
    "jenis_dokumen": "BC 3.0",
    "nomor_surat_cukai": "CK027",
    "nomor_seri_barang": "NSB027",
    "po_date": "2023-01-10",
    "nomor_purchase_order": "PO027",
    "sku_barang": "SKU027",
    "item_name": "Item AA",
    "category": "Category A",
    "qty": 6,
    "unit_measurement": "Pcs",
    "unit_price": 8,
    "country": "USA"
  },
  {
    "tanggal_dokumen_cukai_keluar": "2023-01-28",
    "jenis_dokumen": "BC 3.0",
    "nomor_surat_cukai": "CK028",
    "nomor_seri_barang": "NSB028",
    "po_date": "2023-01-11",
    "nomor_purchase_order": "PO028",
    "sku_barang": "SKU028",
    "item_name": "Item BB",
    "category": "Category B",
    "qty": 8,
    "unit_measurement": "Kg",
    "unit_price": 5,
    "country": "China"
  },
  {
    "tanggal_dokumen_cukai_keluar": "2023-01-29",
    "jenis_dokumen": "BC 2.4",
    "nomor_surat_cukai": "CK029",
    "nomor_seri_barang": "NSB029",
    "po_date": "2023-01-12",
    "nomor_purchase_order": "PO029",
    "sku_barang": "SKU029",
    "item_name": "Item CC",
    "category": "Category C",
    "qty": 14,
    "unit_measurement": "Meter",
    "unit_price": 6,
    "country": "Germany"
  },
  {
    "tanggal_dokumen_cukai_keluar": "2023-01-30",
    "jenis_dokumen": "BC 3.0",
    "nomor_surat_cukai": "CK030",
    "nomor_seri_barang": "NSB030",
    "po_date": "2023-01-13",
    "nomor_purchase_order": "PO030",
    "sku_barang": "SKU030",
    "item_name": "Item DD",
    "category": "Category A",
    "qty": 12,
    "unit_measurement": "Pcs",
    "unit_price": 7,
    "country": "USA"
  },
  {
    "tanggal_dokumen_cukai_keluar": "2023-01-31",
    "jenis_dokumen": "BC 2.0",
    "nomor_surat_cukai": "CK031",
    "nomor_seri_barang": "NSB031",
    "po_date": "2023-01-14",
    "nomor_purchase_order": "PO031",
    "sku_barang": "SKU031",
    "item_name": "Item EE",
    "category": "Category B",
    "qty": 7,
    "unit_measurement": "Kg",
    "unit_price": 9,
    "country": "China"
  },
  {
    "tanggal_dokumen_cukai_keluar": "2023-02-01",
    "jenis_dokumen": "BC 2.4",
    "nomor_surat_cukai": "CK032",
    "nomor_seri_barang": "NSB032",
    "po_date": "2023-01-15",
    "nomor_purchase_order": "PO032",
    "sku_barang": "SKU032",
    "item_name": "Item FF",
    "category": "Category C",
    "qty": 9,
    "unit_measurement": "Meter",
    "unit_price": 6,
    "country": "Germany"
  },
  {
    "tanggal_dokumen_cukai_keluar": "2023-02-02",
    "jenis_dokumen": "BC 2.4",
    "nomor_surat_cukai": "CK033",
    "nomor_seri_barang": "NSB033",
    "po_date": "2023-01-16",
    "nomor_purchase_order": "PO033",
    "sku_barang": "SKU033",
    "item_name": "Item GG",
    "category": "Category A",
    "qty": 8,
    "unit_measurement": "Pcs",
    "unit_price": 5,
    "country": "USA"
  },
  {
    "tanggal_dokumen_cukai_keluar": "2023-02-03",
    "jenis_dokumen": "BC 3.0",
    "nomor_surat_cukai": "CK034",
    "nomor_seri_barang": "NSB034",
    "po_date": "2023-01-17",
    "nomor_purchase_order": "PO034",
    "sku_barang": "SKU034",
    "item_name": "Item HH",
    "category": "Category B",
    "qty": 11,
    "unit_measurement": "Kg",
    "unit_price": 7,
    "country": "China"
  },
  {
    "tanggal_dokumen_cukai_keluar": "2023-02-04",
    "jenis_dokumen": "BC 2.0",
    "nomor_surat_cukai": "CK035",
    "nomor_seri_barang": "NSB035",
    "po_date": "2023-01-18",
    "nomor_purchase_order": "PO035",
    "sku_barang": "SKU035",
    "item_name": "Item II",
    "category": "Category C",
    "qty": 5,
    "unit_measurement": "Meter",
    "unit_price": 8,
    "country": "Germany"
  },
  {
    "tanggal_dokumen_cukai_keluar": "2023-02-05",
    "jenis_dokumen": "BC 2.0",
    "nomor_surat_cukai": "CK036",
    "nomor_seri_barang": "NSB036",
    "po_date": "2023-01-19",
    "nomor_purchase_order": "PO036",
    "sku_barang": "SKU036",
    "item_name": "Item JJ",
    "category": "Category A",
    "qty": 13,
    "unit_measurement": "Pcs",
    "unit_price": 6,
    "country": "USA"
  },
  {
    "tanggal_dokumen_cukai_keluar": "2023-02-06",
    "jenis_dokumen": "BC 2.4",
    "nomor_surat_cukai": "CK037",
    "nomor_seri_barang": "NSB037",
    "po_date": "2023-01-20",
    "nomor_purchase_order": "PO037",
    "sku_barang": "SKU037",
    "item_name": "Item KK",
    "category": "Category B",
    "qty": 10,
    "unit_measurement": "Kg",
    "unit_price": 5,
    "country": "China"
  },
  {
    "tanggal_dokumen_cukai_keluar": "2023-02-07",
    "jenis_dokumen": "BC 3.0",
    "nomor_surat_cukai": "CK038",
    "nomor_seri_barang": "NSB038",
    "po_date": "2023-01-21",
    "nomor_purchase_order": "PO038",
    "sku_barang": "SKU038",
    "item_name": "Item LL",
    "category": "Category C",
    "qty": 15,
    "unit_measurement": "Meter",
    "unit_price": 7,
    "country": "Germany"
  },
  {
    "tanggal_dokumen_cukai_keluar": "2023-02-08",
    "jenis_dokumen": "BC 2.4",
    "nomor_surat_cukai": "CK039",
    "nomor_seri_barang": "NSB039",
    "po_date": "2023-01-22",
    "nomor_purchase_order": "PO039",
    "sku_barang": "SKU039",
    "item_name": "Item MM",
    "category": "Category A",
    "qty": 9,
    "unit_measurement": "Pcs",
    "unit_price": 4,
    "country": "USA"
  },
  {
    "tanggal_dokumen_cukai_keluar": "2023-02-09",
    "jenis_dokumen": "BC 3.0",
    "nomor_surat_cukai": "CK040",
    "nomor_seri_barang": "NSB040",
    "po_date": "2023-01-23",
    "nomor_purchase_order": "PO040",
    "sku_barang": "SKU040",
    "item_name": "Item NN",
    "category": "Category B",
    "qty": 10,
    "unit_measurement": "Kg",
    "unit_price": 6,
    "country": "China"
  }
]