export const __payload = [
  {
    "tanggal_bukti_pengeluaran_barang": "2023-01-01",
    "nomor_bukti_pengeluaran_barang": "BUKTI001",
    "sales_order_date": "2022-12-15",
    "serial_number_sales_order": "SO001",
    "buyer_name": "Buyer A",
    "country": "USA",
    "material_code": "MC001",
    "item_name": "Item A",
    "category": "Category A",
    "qty": 10,
    "unit_measurement": "Pcs",
    "unit_price": 5
  },
  {
    "tanggal_bukti_pengeluaran_barang": "2023-01-02",
    "nomor_bukti_pengeluaran_barang": "BUKTI002",
    "sales_order_date": "2022-12-16",
    "serial_number_sales_order": "SO002",
    "buyer_name": "Buyer B",
    "country": "China",
    "material_code": "MC002",
    "item_name": "Item B",
    "category": "Category B",
    "qty": 15,
    "unit_measurement": "Kg",
    "unit_price": 3
  },
  {
    "tanggal_bukti_pengeluaran_barang": "2023-01-03",
    "nomor_bukti_pengeluaran_barang": "BUKTI003",
    "sales_order_date": "2022-12-17",
    "serial_number_sales_order": "SO003",
    "buyer_name": "Buyer C",
    "country": "USA",
    "material_code": "MC003",
    "item_name": "Item C",
    "category": "Category A",
    "qty": 20,
    "unit_measurement": "Pcs",
    "unit_price": 7
  },
  {
    "tanggal_bukti_pengeluaran_barang": "2023-01-04",
    "nomor_bukti_pengeluaran_barang": "BUKTI004",
    "sales_order_date": "2022-12-18",
    "serial_number_sales_order": "SO004",
    "buyer_name": "Buyer D",
    "country": "Germany",
    "material_code": "MC004",
    "item_name": "Item D",
    "category": "Category C",
    "qty": 5,
    "unit_measurement": "Meter",
    "unit_price": 10
  },
  {
    "tanggal_bukti_pengeluaran_barang": "2023-01-05",
    "nomor_bukti_pengeluaran_barang": "BUKTI005",
    "sales_order_date": "2022-12-19",
    "serial_number_sales_order": "SO005",
    "buyer_name": "Buyer E",
    "country": "China",
    "material_code": "MC005",
    "item_name": "Item E",
    "category": "Category B",
    "qty": 12,
    "unit_measurement": "Kg",
    "unit_price": 8
  },
  {
    "tanggal_bukti_pengeluaran_barang": "2023-01-06",
    "nomor_bukti_pengeluaran_barang": "BUKTI006",
    "sales_order_date": "2022-12-20",
    "serial_number_sales_order": "SO006",
    "buyer_name": "Buyer F",
    "country": "USA",
    "material_code": "MC006",
    "item_name": "Item F",
    "category": "Category A",
    "qty": 8,
    "unit_measurement": "Pcs",
    "unit_price": 6
  },
  {
    "tanggal_bukti_pengeluaran_barang": "2023-01-07",
    "nomor_bukti_pengeluaran_barang": "BUKTI007",
    "sales_order_date": "2022-12-21",
    "serial_number_sales_order": "SO007",
    "buyer_name": "Buyer G",
    "country": "Germany",
    "material_code": "MC007",
    "item_name": "Item G",
    "category": "Category C",
    "qty": 15,
    "unit_measurement": "Meter",
    "unit_price": 12
  },
  {
    "tanggal_bukti_pengeluaran_barang": "2023-01-08",
    "nomor_bukti_pengeluaran_barang": "BUKTI008",
    "sales_order_date": "2022-12-22",
    "serial_number_sales_order": "SO008",
    "buyer_name": "Buyer H",
    "country": "USA",
    "material_code": "MC008",
    "item_name": "Item H",
    "category": "Category A",
    "qty": 6,
    "unit_measurement": "Pcs",
    "unit_price": 9
  },
  {
    "tanggal_bukti_pengeluaran_barang": "2023-01-09",
    "nomor_bukti_pengeluaran_barang": "BUKTI009",
    "sales_order_date": "2022-12-23",
    "serial_number_sales_order": "SO009",
    "buyer_name": "Buyer I",
    "country": "China",
    "material_code": "MC009",
    "item_name": "Item I",
    "category": "Category B",
    "qty": 10,
    "unit_measurement": "Kg",
    "unit_price": 7
  },
  {
    "tanggal_bukti_pengeluaran_barang": "2023-01-10",
    "nomor_bukti_pengeluaran_barang": "BUKTI010",
    "sales_order_date": "2022-12-24",
    "serial_number_sales_order": "SO010",
    "buyer_name": "Buyer J",
    "country": "Germany",
    "material_code": "MC010",
    "item_name": "Item J",
    "category": "Category C",
    "qty": 18,
    "unit_measurement": "Meter",
    "unit_price": 5
  },
  {
    "tanggal_bukti_pengeluaran_barang": "2023-01-11",
    "nomor_bukti_pengeluaran_barang": "BUKTI011",
    "sales_order_date": "2022-12-25",
    "serial_number_sales_order": "SO011",
    "buyer_name": "Buyer K",
    "country": "USA",
    "material_code": "MC011",
    "item_name": "Item K",
    "category": "Category A",
    "qty": 13,
    "unit_measurement": "Pcs",
    "unit_price": 4
  },
  {
    "tanggal_bukti_pengeluaran_barang": "2023-01-12",
    "nomor_bukti_pengeluaran_barang": "BUKTI012",
    "sales_order_date": "2022-12-26",
    "serial_number_sales_order": "SO012",
    "buyer_name": "Buyer L",
    "country": "China",
    "material_code": "MC012",
    "item_name": "Item L",
    "category": "Category B",
    "qty": 7,
    "unit_measurement": "Kg",
    "unit_price": 6
  },
  {
    "tanggal_bukti_pengeluaran_barang": "2023-01-13",
    "nomor_bukti_pengeluaran_barang": "BUKTI013",
    "sales_order_date": "2022-12-27",
    "serial_number_sales_order": "SO013",
    "buyer_name": "Buyer M",
    "country": "USA",
    "material_code": "MC013",
    "item_name": "Item M",
    "category": "Category A",
    "qty": 10,
    "unit_measurement": "Pcs",
    "unit_price": 3
  },
  {
    "tanggal_bukti_pengeluaran_barang": "2023-01-14",
    "nomor_bukti_pengeluaran_barang": "BUKTI014",
    "sales_order_date": "2022-12-28",
    "serial_number_sales_order": "SO014",
    "buyer_name": "Buyer N",
    "country": "Germany",
    "material_code": "MC014",
    "item_name": "Item N",
    "category": "Category C",
    "qty": 16,
    "unit_measurement": "Meter",
    "unit_price": 8
  },
  {
    "tanggal_bukti_pengeluaran_barang": "2023-01-15",
    "nomor_bukti_pengeluaran_barang": "BUKTI015",
    "sales_order_date": "2022-12-29",
    "serial_number_sales_order": "SO015",
    "buyer_name": "Buyer O",
    "country": "China",
    "material_code": "MC015",
    "item_name": "Item O",
    "category": "Category B",
    "qty": 9,
    "unit_measurement": "Kg",
    "unit_price": 5
  },
  {
    "tanggal_bukti_pengeluaran_barang": "2023-01-16",
    "nomor_bukti_pengeluaran_barang": "BUKTI016",
    "sales_order_date": "2022-12-30",
    "serial_number_sales_order": "SO016",
    "buyer_name": "Buyer P",
    "country": "USA",
    "material_code": "MC016",
    "item_name": "Item P",
    "category": "Category A",
    "qty": 11,
    "unit_measurement": "Pcs",
    "unit_price": 4
  },
  {
    "tanggal_bukti_pengeluaran_barang": "2023-01-17",
    "nomor_bukti_pengeluaran_barang": "BUKTI017",
    "sales_order_date": "2022-12-31",
    "serial_number_sales_order": "SO017",
    "buyer_name": "Buyer Q",
    "country": "China",
    "material_code": "MC017",
    "item_name": "Item Q",
    "category": "Category B",
    "qty": 13,
    "unit_measurement": "Kg",
    "unit_price": 6
  },
  {
    "tanggal_bukti_pengeluaran_barang": "2023-01-18",
    "nomor_bukti_pengeluaran_barang": "BUKTI018",
    "sales_order_date": "2023-01-01",
    "serial_number_sales_order": "SO018",
    "buyer_name": "Buyer R",
    "country": "Germany",
    "material_code": "MC018",
    "item_name": "Item R",
    "category": "Category C",
    "qty": 14,
    "unit_measurement": "Meter",
    "unit_price": 9
  },
  {
    "tanggal_bukti_pengeluaran_barang": "2023-01-19",
    "nomor_bukti_pengeluaran_barang": "BUKTI019",
    "sales_order_date": "2023-01-02",
    "serial_number_sales_order": "SO019",
    "buyer_name": "Buyer S",
    "country": "USA",
    "material_code": "MC019",
    "item_name": "Item S",
    "category": "Category A",
    "qty": 7,
    "unit_measurement": "Pcs",
    "unit_price": 5
  },
  {
    "tanggal_bukti_pengeluaran_barang": "2023-01-20",
    "nomor_bukti_pengeluaran_barang": "BUKTI020",
    "sales_order_date": "2023-01-03",
    "serial_number_sales_order": "SO020",
    "buyer_name": "Buyer T",
    "country": "China",
    "material_code": "MC020",
    "item_name": "Item T",
    "category": "Category B",
    "qty": 9,
    "unit_measurement": "Kg",
    "unit_price": 7
  },
  {
    "tanggal_bukti_pengeluaran_barang": "2023-01-21",
    "nomor_bukti_pengeluaran_barang": "BUKTI021",
    "sales_order_date": "2023-01-04",
    "serial_number_sales_order": "SO021",
    "buyer_name": "Buyer U",
    "country": "Germany",
    "material_code": "MC021",
    "item_name": "Item U",
    "category": "Category C",
    "qty": 11,
    "unit_measurement": "Meter",
    "unit_price": 6
  },
  {
    "tanggal_bukti_pengeluaran_barang": "2023-01-22",
    "nomor_bukti_pengeluaran_barang": "BUKTI022",
    "sales_order_date": "2023-01-05",
    "serial_number_sales_order": "SO022",
    "buyer_name": "Buyer V",
    "country": "USA",
    "material_code": "MC022",
    "item_name": "Item V",
    "category": "Category A",
    "qty": 12,
    "unit_measurement": "Pcs",
    "unit_price": 8
  },
  {
    "tanggal_bukti_pengeluaran_barang": "2023-01-23",
    "nomor_bukti_pengeluaran_barang": "BUKTI023",
    "sales_order_date": "2023-01-06",
    "serial_number_sales_order": "SO023",
    "buyer_name": "Buyer W",
    "country": "China",
    "material_code": "MC023",
    "item_name": "Item W",
    "category": "Category B",
    "qty": 8,
    "unit_measurement": "Kg",
    "unit_price": 6
  },
  {
    "tanggal_bukti_pengeluaran_barang": "2023-01-24",
    "nomor_bukti_pengeluaran_barang": "BUKTI024",
    "sales_order_date": "2023-01-07",
    "serial_number_sales_order": "SO024",
    "buyer_name": "Buyer X",
    "country": "USA",
    "material_code": "MC024",
    "item_name": "Item X",
    "category": "Category A",
    "qty": 10,
    "unit_measurement": "Pcs",
    "unit_price": 5
  },
  {
    "tanggal_bukti_pengeluaran_barang": "2023-01-25",
    "nomor_bukti_pengeluaran_barang": "BUKTI025",
    "sales_order_date": "2023-01-08",
    "serial_number_sales_order": "SO025",
    "buyer_name": "Buyer Y",
    "country": "Germany",
    "material_code": "MC025",
    "item_name": "Item Y",
    "category": "Category C",
    "qty": 9,
    "unit_measurement": "Meter",
    "unit_price": 7
  },
  {
    "tanggal_bukti_pengeluaran_barang": "2023-01-26",
    "nomor_bukti_pengeluaran_barang": "BUKTI026",
    "sales_order_date": "2023-01-09",
    "serial_number_sales_order": "SO026",
    "buyer_name": "Buyer Z",
    "country": "China",
    "material_code": "MC026",
    "item_name": "Item Z",
    "category": "Category B",
    "qty": 15,
    "unit_measurement": "Kg",
    "unit_price": 4
  },
  {
    "tanggal_bukti_pengeluaran_barang": "2023-01-27",
    "nomor_bukti_pengeluaran_barang": "BUKTI027",
    "sales_order_date": "2023-01-10",
    "serial_number_sales_order": "SO027",
    "buyer_name": "Buyer AA",
    "country": "USA",
    "material_code": "MC027",
    "item_name": "Item AA",
    "category": "Category A",
    "qty": 6,
    "unit_measurement": "Pcs",
    "unit_price": 8
  },
  {
    "tanggal_bukti_pengeluaran_barang": "2023-01-28",
    "nomor_bukti_pengeluaran_barang": "BUKTI028",
    "sales_order_date": "2023-01-11",
    "serial_number_sales_order": "SO028",
    "buyer_name": "Buyer BB",
    "country": "China",
    "material_code": "MC028",
    "item_name": "Item BB",
    "category": "Category B",
    "qty": 8,
    "unit_measurement": "Kg",
    "unit_price": 5
  },
  {
    "tanggal_bukti_pengeluaran_barang": "2023-01-29",
    "nomor_bukti_pengeluaran_barang": "BUKTI029",
    "sales_order_date": "2023-01-12",
    "serial_number_sales_order": "SO029",
    "buyer_name": "Buyer CC",
    "country": "Germany",
    "material_code": "MC029",
    "item_name": "Item CC",
    "category": "Category C",
    "qty": 14,
    "unit_measurement": "Meter",
    "unit_price": 6
  },
  {
    "tanggal_bukti_pengeluaran_barang": "2023-01-30",
    "nomor_bukti_pengeluaran_barang": "BUKTI030",
    "sales_order_date": "2023-01-13",
    "serial_number_sales_order": "SO030",
    "buyer_name": "Buyer DD",
    "country": "USA",
    "material_code": "MC030",
    "item_name": "Item DD",
    "category": "Category A",
    "qty": 12,
    "unit_measurement": "Pcs",
    "unit_price": 7
  },
  {
    "tanggal_bukti_pengeluaran_barang": "2023-01-31",
    "nomor_bukti_pengeluaran_barang": "BUKTI031",
    "sales_order_date": "2023-01-14",
    "serial_number_sales_order": "SO031",
    "buyer_name": "Buyer EE",
    "country": "China",
    "material_code": "MC031",
    "item_name": "Item EE",
    "category": "Category B",
    "qty": 7,
    "unit_measurement": "Kg",
    "unit_price": 9
  },
  {
    "tanggal_bukti_pengeluaran_barang": "2023-02-01",
    "nomor_bukti_pengeluaran_barang": "BUKTI032",
    "sales_order_date": "2023-01-15",
    "serial_number_sales_order": "SO032",
    "buyer_name": "Buyer FF",
    "country": "Germany",
    "material_code": "MC032",
    "item_name": "Item FF",
    "category": "Category C",
    "qty": 9,
    "unit_measurement": "Meter",
    "unit_price": 6
  },
  {
    "tanggal_bukti_pengeluaran_barang": "2023-02-02",
    "nomor_bukti_pengeluaran_barang": "BUKTI033",
    "sales_order_date": "2023-01-16",
    "serial_number_sales_order": "SO033",
    "buyer_name": "Buyer GG",
    "country": "USA",
    "material_code": "MC033",
    "item_name": "Item GG",
    "category": "Category A",
    "qty": 8,
    "unit_measurement": "Pcs",
    "unit_price": 5
  },
  {
    "tanggal_bukti_pengeluaran_barang": "2023-02-03",
    "nomor_bukti_pengeluaran_barang": "BUKTI034",
    "sales_order_date": "2023-01-17",
    "serial_number_sales_order": "SO034",
    "buyer_name": "Buyer HH",
    "country": "China",
    "material_code": "MC034",
    "item_name": "Item HH",
    "category": "Category B",
    "qty": 11,
    "unit_measurement": "Kg",
    "unit_price": 7
  },
  {
    "tanggal_bukti_pengeluaran_barang": "2023-02-04",
    "nomor_bukti_pengeluaran_barang": "BUKTI035",
    "sales_order_date": "2023-01-18",
    "serial_number_sales_order": "SO035",
    "buyer_name": "Buyer II",
    "country": "Germany",
    "material_code": "MC035",
    "item_name": "Item II",
    "category": "Category C",
    "qty": 5,
    "unit_measurement": "Meter",
    "unit_price": 8
  },
  {
    "tanggal_bukti_pengeluaran_barang": "2023-02-05",
    "nomor_bukti_pengeluaran_barang": "BUKTI036",
    "sales_order_date": "2023-01-19",
    "serial_number_sales_order": "SO036",
    "buyer_name": "Buyer JJ",
    "country": "USA",
    "material_code": "MC036",
    "item_name": "Item JJ",
    "category": "Category A",
    "qty": 13,
    "unit_measurement": "Pcs",
    "unit_price": 6
  },
  {
    "tanggal_bukti_pengeluaran_barang": "2023-02-06",
    "nomor_bukti_pengeluaran_barang": "BUKTI037",
    "sales_order_date": "2023-01-20",
    "serial_number_sales_order": "SO037",
    "buyer_name": "Buyer KK",
    "country": "China",
    "material_code": "MC037",
    "item_name": "Item KK",
    "category": "Category B",
    "qty": 10,
    "unit_measurement": "Kg",
    "unit_price": 5
  },
  {
    "tanggal_bukti_pengeluaran_barang": "2023-02-07",
    "nomor_bukti_pengeluaran_barang": "BUKTI038",
    "sales_order_date": "2023-01-21",
    "serial_number_sales_order": "SO038",
    "buyer_name": "Buyer LL",
    "country": "Germany",
    "material_code": "MC038",
    "item_name": "Item LL",
    "category": "Category C",
    "qty": 15,
    "unit_measurement": "Meter",
    "unit_price": 7
  },
  {
    "tanggal_bukti_pengeluaran_barang": "2023-02-08",
    "nomor_bukti_pengeluaran_barang": "BUKTI039",
    "sales_order_date": "2023-01-22",
    "serial_number_sales_order": "SO039",
    "buyer_name": "Buyer MM",
    "country": "USA",
    "material_code": "MC039",
    "item_name": "Item MM",
    "category": "Category A",
    "qty": 9,
    "unit_measurement": "Pcs",
    "unit_price": 4
  },
  {
    "tanggal_bukti_pengeluaran_barang": "2023-02-09",
    "nomor_bukti_pengeluaran_barang": "BUKTI040",
    "sales_order_date": "2023-01-23",
    "serial_number_sales_order": "SO040",
    "buyer_name": "Buyer NN",
    "country": "China",
    "material_code": "MC040",
    "item_name": "Item NN",
    "category": "Category B",
    "qty": 10,
    "unit_measurement": "Kg",
    "unit_price": 6
  }
]