export const __payload = [
  {
    "nomor_bukti": "BUKTI001",
    "tanggal_bukti": "2023-01-01",
    "id": 1,
    "item_name": "Item A",
    "category_name": "Category A",
    "unit_measurement": "Pcs",
    "total_output": 10,
    "sub_kontrak": "Subkontrak A",
    "current_position": "Position A"
  },
  {
    "nomor_bukti": "BUKTI002",
    "tanggal_bukti": "2023-01-02",
    "id": 2,
    "item_name": "Item B",
    "category_name": "Category B",
    "unit_measurement": "Kg",
    "total_output": 15,
    "sub_kontrak": "Subkontrak B",
    "current_position": "Position B"
  },
  {
    "nomor_bukti": "BUKTI003",
    "tanggal_bukti": "2023-01-03",
    "id": 3,
    "item_name": "Item C",
    "category_name": "Category A",
    "unit_measurement": "Pcs",
    "total_output": 20,
    "sub_kontrak": "Subkontrak C",
    "current_position": "Position C"
  },
  {
    "nomor_bukti": "BUKTI004",
    "tanggal_bukti": "2023-01-04",
    "id": 4,
    "item_name": "Item D",
    "category_name": "Category C",
    "unit_measurement": "Meter",
    "total_output": 5,
    "sub_kontrak": "Subkontrak D",
    "current_position": "Position D"
  },
  {
    "nomor_bukti": "BUKTI005",
    "tanggal_bukti": "2023-01-05",
    "id": 5,
    "item_name": "Item E",
    "category_name": "Category B",
    "unit_measurement": "Kg",
    "total_output": 12,
    "sub_kontrak": "Subkontrak E",
    "current_position": "Position E"
  },
  {
    "nomor_bukti": "BUKTI006",
    "tanggal_bukti": "2023-01-06",
    "id": 6,
    "item_name": "Item F",
    "category_name": "Category A",
    "unit_measurement": "Pcs",
    "total_output": 8,
    "sub_kontrak": "Subkontrak F",
    "current_position": "Position F"
  },
  {
    "nomor_bukti": "BUKTI007",
    "tanggal_bukti": "2023-01-07",
    "id": 7,
    "item_name": "Item G",
    "category_name": "Category C",
    "unit_measurement": "Meter",
    "total_output": 15,
    "sub_kontrak": "Subkontrak G",
    "current_position": "Position G"
  },
  {
    "nomor_bukti": "BUKTI008",
    "tanggal_bukti": "2023-01-08",
    "id": 8,
    "item_name": "Item H",
    "category_name": "Category A",
    "unit_measurement": "Pcs",
    "total_output": 6,
    "sub_kontrak": "Subkontrak H",
    "current_position": "Position H"
  },
  {
    "nomor_bukti": "BUKTI009",
    "tanggal_bukti": "2023-01-09",
    "id": 9,
    "item_name": "Item I",
    "category_name": "Category B",
    "unit_measurement": "Kg",
    "total_output": 10,
    "sub_kontrak": "Subkontrak I",
    "current_position": "Position I"
  },
  {
    "nomor_bukti": "BUKTI010",
    "tanggal_bukti": "2023-01-10",
    "id": 10,
    "item_name": "Item J",
    "category_name": "Category C",
    "unit_measurement": "Meter",
    "total_output": 18,
    "sub_kontrak": "Subkontrak J",
    "current_position": "Position J"
  },
  {
    "nomor_bukti": "BUKTI011",
    "tanggal_bukti": "2023-01-11",
    "id": 11,
    "item_name": "Item K",
    "category_name": "Category A",
    "unit_measurement": "Pcs",
    "total_output": 13,
    "sub_kontrak": "Subkontrak K",
    "current_position": "Position K"
  },
  {
    "nomor_bukti": "BUKTI012",
    "tanggal_bukti": "2023-01-12",
    "id": 12,
    "item_name": "Item L",
    "category_name": "Category B",
    "unit_measurement": "Kg",
    "total_output": 7,
    "sub_kontrak": "Subkontrak L",
    "current_position": "Position L"
  },
  {
    "nomor_bukti": "BUKTI013",
    "tanggal_bukti": "2023-01-13",
    "id": 13,
    "item_name": "Item M",
    "category_name": "Category A",
    "unit_measurement": "Pcs",
    "total_output": 10,
    "sub_kontrak": "Subkontrak M",
    "current_position": "Position M"
  },
  {
    "nomor_bukti": "BUKTI014",
    "tanggal_bukti": "2023-01-14",
    "id": 14,
    "item_name": "Item N",
    "category_name": "Category C",
    "unit_measurement": "Meter",
    "total_output": 16,
    "sub_kontrak": "Subkontrak N",
    "current_position": "Position N"
  },
  {
    "nomor_bukti": "BUKTI015",
    "tanggal_bukti": "2023-01-15",
    "id": 15,
    "item_name": "Item O",
    "category_name": "Category B",
    "unit_measurement": "Kg",
    "total_output": 9,
    "sub_kontrak": "Subkontrak O",
    "current_position": "Position O"
  },
  {
    "nomor_bukti": "BUKTI016",
    "tanggal_bukti": "2023-01-16",
    "id": 16,
    "item_name": "Item P",
    "category_name": "Category A",
    "unit_measurement": "Pcs",
    "total_output": 11,
    "sub_kontrak": "Subkontrak P",
    "current_position": "Position P"
  },
  {
    "nomor_bukti": "BUKTI017",
    "tanggal_bukti": "2023-01-17",
    "id": 17,
    "item_name": "Item Q",
    "category_name": "Category B",
    "unit_measurement": "Kg",
    "total_output": 13,
    "sub_kontrak": "Subkontrak Q",
    "current_position": "Position Q"
  },
  {
    "nomor_bukti": "BUKTI018",
    "tanggal_bukti": "2023-01-18",
    "id": 18,
    "item_name": "Item R",
    "category_name": "Category C",
    "unit_measurement": "Meter",
    "total_output": 14,
    "sub_kontrak": "Subkontrak R",
    "current_position": "Position R"
  },
  {
    "nomor_bukti": "BUKTI019",
    "tanggal_bukti": "2023-01-19",
    "id": 19,
    "item_name": "Item S",
    "category_name": "Category A",
    "unit_measurement": "Pcs",
    "total_output": 7,
    "sub_kontrak": "Subkontrak S",
    "current_position": "Position S"
  },
  {
    "nomor_bukti": "BUKTI020",
    "tanggal_bukti": "2023-01-20",
    "id": 20,
    "item_name": "Item T",
    "category_name": "Category B",
    "unit_measurement": "Kg",
    "total_output": 9,
    "sub_kontrak": "Subkontrak T",
    "current_position": "Position T"
  },
  {
    "nomor_bukti": "BUKTI021",
    "tanggal_bukti": "2023-01-21",
    "id": 21,
    "item_name": "Item U",
    "category_name": "Category C",
    "unit_measurement": "Meter",
    "total_output": 11,
    "sub_kontrak": "Subkontrak U",
    "current_position": "Position U"
  },
  {
    "nomor_bukti": "BUKTI022",
    "tanggal_bukti": "2023-01-22",
    "id": 22,
    "item_name": "Item V",
    "category_name": "Category A",
    "unit_measurement": "Pcs",
    "total_output": 12,
    "sub_kontrak": "Subkontrak V",
    "current_position": "Position V"
  },
  {
    "nomor_bukti": "BUKTI023",
    "tanggal_bukti": "2023-01-23",
    "id": 23,
    "item_name": "Item W",
    "category_name": "Category B",
    "unit_measurement": "Kg",
    "total_output": 8,
    "sub_kontrak": "Subkontrak W",
    "current_position": "Position W"
  },
  {
    "nomor_bukti": "BUKTI024",
    "tanggal_bukti": "2023-01-24",
    "id": 24,
    "item_name": "Item X",
    "category_name": "Category A",
    "unit_measurement": "Pcs",
    "total_output": 10,
    "sub_kontrak": "Subkontrak X",
    "current_position": "Position X"
  },
  {
    "nomor_bukti": "BUKTI025",
    "tanggal_bukti": "2023-01-25",
    "id": 25,
    "item_name": "Item Y",
    "category_name": "Category C",
    "unit_measurement": "Meter",
    "total_output": 9,
    "sub_kontrak": "Subkontrak Y",
    "current_position": "Position Y"
  },
  {
    "nomor_bukti": "BUKTI026",
    "tanggal_bukti": "2023-01-26",
    "id": 26,
    "item_name": "Item Z",
    "category_name": "Category B",
    "unit_measurement": "Kg",
    "total_output": 15,
    "sub_kontrak": "Subkontrak Z",
    "current_position": "Position Z"
  },
  {
    "nomor_bukti": "BUKTI027",
    "tanggal_bukti": "2023-01-27",
    "id": 27,
    "item_name": "Item AA",
    "category_name": "Category A",
    "unit_measurement": "Pcs",
    "total_output": 6,
    "sub_kontrak": "Subkontrak AA",
    "current_position": "Position AA"
  },
  {
    "nomor_bukti": "BUKTI028",
    "tanggal_bukti": "2023-01-28",
    "id": 28,
    "item_name": "Item BB",
    "category_name": "Category B",
    "unit_measurement": "Kg",
    "total_output": 8,
    "sub_kontrak": "Subkontrak BB",
    "current_position": "Position BB"
  },
  {
    "nomor_bukti": "BUKTI029",
    "tanggal_bukti": "2023-01-29",
    "id": 29,
    "item_name": "Item CC",
    "category_name": "Category C",
    "unit_measurement": "Meter",
    "total_output": 14,
    "sub_kontrak": "Subkontrak CC",
    "current_position": "Position CC"
  },
  {
    "nomor_bukti": "BUKTI030",
    "tanggal_bukti": "2023-01-30",
    "id": 30,
    "item_name": "Item DD",
    "category_name": "Category A",
    "unit_measurement": "Pcs",
    "total_output": 12,
    "sub_kontrak": "Subkontrak DD",
    "current_position": "Position DD"
  },
  {
    "nomor_bukti": "BUKTI031",
    "tanggal_bukti": "2023-01-31",
    "id": 31,
    "item_name": "Item EE",
    "category_name": "Category B",
    "unit_measurement": "Kg",
    "total_output": 7,
    "sub_kontrak": "Subkontrak EE",
    "current_position": "Position EE"
  },
  {
    "nomor_bukti": "BUKTI032",
    "tanggal_bukti": "2023-02-01",
    "id": 32,
    "item_name": "Item FF",
    "category_name": "Category C",
    "unit_measurement": "Meter",
    "total_output": 9,
    "sub_kontrak": "Subkontrak FF",
    "current_position": "Position FF"
  },
  {
    "nomor_bukti": "BUKTI033",
    "tanggal_bukti": "2023-02-02",
    "id": 33,
    "item_name": "Item GG",
    "category_name": "Category A",
    "unit_measurement": "Pcs",
    "total_output": 8,
    "sub_kontrak": "Subkontrak GG",
    "current_position": "Position GG"
  },
  {
    "nomor_bukti": "BUKTI034",
    "tanggal_bukti": "2023-02-03",
    "id": 34,
    "item_name": "Item HH",
    "category_name": "Category B",
    "unit_measurement": "Kg",
    "total_output": 11,
    "sub_kontrak": "Subkontrak HH",
    "current_position": "Position HH"
  },
  {
    "nomor_bukti": "BUKTI035",
    "tanggal_bukti": "2023-02-04",
    "id": 35,
    "item_name": "Item II",
    "category_name": "Category C",
    "unit_measurement": "Meter",
    "total_output": 5,
    "sub_kontrak": "Subkontrak II",
    "current_position": "Position II"
  },
  {
    "nomor_bukti": "BUKTI036",
    "tanggal_bukti": "2023-02-05",
    "id": 36,
    "item_name": "Item JJ",
    "category_name": "Category A",
    "unit_measurement": "Pcs",
    "total_output": 13,
    "sub_kontrak": "Subkontrak JJ",
    "current_position": "Position JJ"
  },
  {
    "nomor_bukti": "BUKTI037",
    "tanggal_bukti": "2023-02-06",
    "id": 37,
    "item_name": "Item KK",
    "category_name": "Category B",
    "unit_measurement": "Kg",
    "total_output": 10,
    "sub_kontrak": "Subkontrak KK",
    "current_position": "Position KK"
  },
  {
    "nomor_bukti": "BUKTI038",
    "tanggal_bukti": "2023-02-07",
    "id": 38,
    "item_name": "Item LL",
    "category_name": "Category C",
    "unit_measurement": "Meter",
    "total_output": 15,
    "sub_kontrak": "Subkontrak LL",
    "current_position": "Position LL"
  },
  {
    "nomor_bukti": "BUKTI039",
    "tanggal_bukti": "2023-02-08",
    "id": 39,
    "item_name": "Item MM",
    "category_name": "Category A",
    "unit_measurement": "Pcs",
    "total_output": 9,
    "sub_kontrak": "Subkontrak MM",
    "current_position": "Position MM"
  },
  {
    "nomor_bukti": "BUKTI040",
    "tanggal_bukti": "2023-02-09",
    "id": 40,
    "item_name": "Item NN",
    "category_name": "Category B",
    "unit_measurement": "Kg",
    "total_output": 10,
    "sub_kontrak": "Subkontrak NN",
    "current_position": "Position NN"
  }
]