-- MySQL Script generated by MySQL Workbench
-- Sun Feb 20 13:55:57 2022
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sakila
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bsi_new_model
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bsi_new_model` DEFAULT CHARACTER SET latin1 ;

-- -----------------------------------------------------
-- Table `bsi_new_model`.`service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bsi_new_model`.`service` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bsi_new_model`.`goods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bsi_new_model`.`goods` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bsi_new_model`.`part`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bsi_new_model`.`part` (
  `id` INT NOT NULL,
  `part_type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bsi_new_model`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bsi_new_model`.`product` (
  `id` INT NOT NULL,
  `product_type_id` INT NULL,
  `name` VARCHAR(45) NULL,
  `part_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_service1_idx` (`product_type_id` ASC),
  INDEX `fk_product_part1_idx` (`part_id` ASC),
  CONSTRAINT `fk_product_service1`
    FOREIGN KEY (`product_type_id`)
    REFERENCES `bsi_new_model`.`service` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_goods1`
    FOREIGN KEY (`product_type_id`)
    REFERENCES `bsi_new_model`.`goods` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_part1`
    FOREIGN KEY (`part_id`)
    REFERENCES `bsi_new_model`.`part` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `bsi_new_model` ;

-- -----------------------------------------------------
-- Table `bsi_new_model`.`sales_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bsi_new_model`.`sales_order` (
  `id` INT NOT NULL,
  `order_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sales_order_order1_idx` (`order_id` ASC),
  CONSTRAINT `fk_sales_order_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `bsi_new_model`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bsi_new_model`.`purchase_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bsi_new_model`.`purchase_order` (
  `id` INT NOT NULL,
  `order_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_purchase_order_order1_idx` (`order_id` ASC),
  CONSTRAINT `fk_purchase_order_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `bsi_new_model`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bsi_new_model`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bsi_new_model`.`order` (
  `id` INT NOT NULL,
  `order_type_id` INT NULL,
  `creation_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_sales_order1_idx` (`order_type_id` ASC),
  CONSTRAINT `fk_order_sales_order1`
    FOREIGN KEY (`order_type_id`)
    REFERENCES `bsi_new_model`.`sales_order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_purchase_order1`
    FOREIGN KEY (`order_type_id`)
    REFERENCES `bsi_new_model`.`purchase_order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bsi_new_model`.`order_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bsi_new_model`.`order_item` (
  `id` INT NOT NULL,
  `order_id` INT NOT NULL,
  `qty` VARCHAR(45) NULL,
  `unit_price` VARCHAR(45) NULL,
  `shipment_estimated` VARCHAR(45) NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`id`, `order_id`),
  INDEX `fk_order_item_order1_idx` (`order_id` ASC),
  INDEX `fk_order_item_product1_idx` (`product_id` ASC),
  CONSTRAINT `fk_order_item_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `bsi_new_model`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_item_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `bsi_new_model`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bsi_new_model`.`order_association`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bsi_new_model`.`order_association` (
  `sales_order_id` INT NOT NULL,
  `purchase_order_id` INT NOT NULL,
  INDEX `fk_order_association_sales_order_idx` (`sales_order_id` ASC),
  INDEX `fk_order_association_purchase_order1_idx` (`purchase_order_id` ASC),
  CONSTRAINT `fk_order_association_sales_order`
    FOREIGN KEY (`sales_order_id`)
    REFERENCES `bsi_new_model`.`sales_order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_association_purchase_order1`
    FOREIGN KEY (`purchase_order_id`)
    REFERENCES `bsi_new_model`.`purchase_order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bsi_new_model`.`order_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bsi_new_model`.`order_status` (
  `id` INT NOT NULL,
  `status_type` VARCHAR(45) NULL,
  `create_time` VARCHAR(45) NULL,
  `order_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_status_order1_idx` (`order_id` ASC),
  CONSTRAINT `fk_order_status_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `bsi_new_model`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bsi_new_model`.`order_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bsi_new_model`.`order_role` (
  `id` INT NOT NULL,
  `order_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_role_order1_idx` (`order_id` ASC),
  CONSTRAINT `fk_order_role_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `bsi_new_model`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bsi_new_model`.`agreement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bsi_new_model`.`agreement` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bsi_new_model`.`agreement_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bsi_new_model`.`agreement_item` (
  `id` INT NOT NULL,
  `agreement_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_agreement_item_agreement1_idx` (`agreement_id` ASC),
  CONSTRAINT `fk_agreement_item_agreement1`
    FOREIGN KEY (`agreement_id`)
    REFERENCES `bsi_new_model`.`agreement` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bsi_new_model`.`price_component`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bsi_new_model`.`price_component` (
  `id` INT NOT NULL,
  `agreement_item_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_price_component_agreement_item1_idx` (`agreement_item_id` ASC),
  CONSTRAINT `fk_price_component_agreement_item1`
    FOREIGN KEY (`agreement_item_id`)
    REFERENCES `bsi_new_model`.`agreement_item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bsi_new_model`.`product_feature`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bsi_new_model`.`product_feature` (
  `product_feature_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `color` VARCHAR(45) NULL,
  `size` VARCHAR(45) NULL,
  `brand` VARCHAR(45) NULL,
  `price_component_id` INT NOT NULL,
  PRIMARY KEY (`product_feature_id`, `product_id`),
  INDEX `fk_product_feature_product1_idx` (`product_id` ASC),
  INDEX `fk_product_feature_price_component1_idx` (`price_component_id` ASC),
  CONSTRAINT `fk_product_feature_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `bsi_new_model`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_feature_price_component1`
    FOREIGN KEY (`price_component_id`)
    REFERENCES `bsi_new_model`.`price_component` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bsi_new_model`.`inventory_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bsi_new_model`.`inventory_type` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bsi_new_model`.`factory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bsi_new_model`.`factory` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bsi_new_model`.`inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bsi_new_model`.`inventory` (
  `id` INT NOT NULL,
  `inventory_type_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `qty_on_hand` INT NULL,
  `factory_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_inventory_inventory_type1_idx` (`inventory_type_id` ASC),
  INDEX `fk_inventory_product1_idx` (`product_id` ASC),
  INDEX `fk_inventory_factory1_idx` (`factory_id` ASC),
  CONSTRAINT `fk_inventory_inventory_type1`
    FOREIGN KEY (`inventory_type_id`)
    REFERENCES `bsi_new_model`.`inventory_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inventory_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `bsi_new_model`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inventory_factory1`
    FOREIGN KEY (`factory_id`)
    REFERENCES `bsi_new_model`.`factory` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bsi_new_model`.`factory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bsi_new_model`.`factory` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bsi_new_model`.`part_bom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bsi_new_model`.`part_bom` (
  `id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `qty_used` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `product_id`),
  INDEX `fk_part_bom_product1_idx` (`product_id` ASC),
  CONSTRAINT `fk_part_bom_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `bsi_new_model`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bsi_new_model`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bsi_new_model`.`person` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bsi_new_model`.`organization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bsi_new_model`.`organization` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bsi_new_model`.`agreement_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bsi_new_model`.`agreement_role` (
  `id` INT NOT NULL,
  `agreement_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_agreement_role_agreement1_idx` (`agreement_id` ASC),
  CONSTRAINT `fk_agreement_role_agreement1`
    FOREIGN KEY (`agreement_id`)
    REFERENCES `bsi_new_model`.`agreement` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bsi_new_model`.`party`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bsi_new_model`.`party` (
  `id` INT NOT NULL,
  `party_type` INT NULL,
  `agreement_role_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_party_person1_idx` (`party_type` ASC),
  INDEX `fk_party_agreement_role1_idx` (`agreement_role_id` ASC),
  CONSTRAINT `fk_party_person1`
    FOREIGN KEY (`party_type`)
    REFERENCES `bsi_new_model`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_party_organization1`
    FOREIGN KEY (`party_type`)
    REFERENCES `bsi_new_model`.`organization` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_party_agreement_role1`
    FOREIGN KEY (`agreement_role_id`)
    REFERENCES `bsi_new_model`.`agreement_role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bsi_new_model`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bsi_new_model`.`status` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bsi_new_model`.`relantionship`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bsi_new_model`.`relantionship` (
  `id` INT NOT NULL,
  `status_id` INT NOT NULL,
  PRIMARY KEY (`id`, `status_id`),
  INDEX `fk_relantionship_status1_idx` (`status_id` ASC),
  CONSTRAINT `fk_relantionship_status1`
    FOREIGN KEY (`status_id`)
    REFERENCES `bsi_new_model`.`status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bsi_new_model`.`party_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bsi_new_model`.`party_roles` (
  `id` INT NOT NULL,
  `party_id` INT NOT NULL,
  `relantionship_id` INT NOT NULL,
  PRIMARY KEY (`id`, `relantionship_id`),
  INDEX `fk_party_roles_party1_idx` (`party_id` ASC),
  INDEX `fk_party_roles_relantionship1_idx` (`relantionship_id` ASC),
  CONSTRAINT `fk_party_roles_party1`
    FOREIGN KEY (`party_id`)
    REFERENCES `bsi_new_model`.`party` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_party_roles_relantionship1`
    FOREIGN KEY (`relantionship_id`)
    REFERENCES `bsi_new_model`.`relantionship` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bsi_new_model`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bsi_new_model`.`address` (
  `id` INT NOT NULL,
  `party_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_address_party1_idx` (`party_id` ASC),
  CONSTRAINT `fk_address_party1`
    FOREIGN KEY (`party_id`)
    REFERENCES `bsi_new_model`.`party` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bsi_new_model`.`order_shipment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bsi_new_model`.`order_shipment` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bsi_new_model`.`item_issuance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bsi_new_model`.`item_issuance` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bsi_new_model`.`shipment_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bsi_new_model`.`shipment_item` (
  `id` INT NOT NULL,
  `order_shipment_id` INT NOT NULL,
  `item_issuance_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_shipment_item_order_shipment1_idx` (`order_shipment_id` ASC),
  INDEX `fk_shipment_item_item_issuance1_idx` (`item_issuance_id` ASC),
  CONSTRAINT `fk_shipment_item_order_shipment1`
    FOREIGN KEY (`order_shipment_id`)
    REFERENCES `bsi_new_model`.`order_shipment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shipment_item_item_issuance1`
    FOREIGN KEY (`item_issuance_id`)
    REFERENCES `bsi_new_model`.`item_issuance` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bsi_new_model`.`shipment_receipt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bsi_new_model`.`shipment_receipt` (
  `id` INT NOT NULL,
  `order_shipment_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_shipment_receipt_order_shipment1_idx` (`order_shipment_id` ASC),
  CONSTRAINT `fk_shipment_receipt_order_shipment1`
    FOREIGN KEY (`order_shipment_id`)
    REFERENCES `bsi_new_model`.`order_shipment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bsi_new_model`.`shipment_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bsi_new_model`.`shipment_role` (
  `id` INT NOT NULL,
  `shipment_receipt_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_shipment_role_shipment_receipt1_idx` (`shipment_receipt_id` ASC),
  CONSTRAINT `fk_shipment_role_shipment_receipt1`
    FOREIGN KEY (`shipment_receipt_id`)
    REFERENCES `bsi_new_model`.`shipment_receipt` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bsi_new_model`.`shipment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bsi_new_model`.`shipment` (
  `shipment_item_id` INT NOT NULL,
  INDEX `fk_shipment_shipment_item1_idx` (`shipment_item_id` ASC),
  CONSTRAINT `fk_shipment_shipment_item1`
    FOREIGN KEY (`shipment_item_id`)
    REFERENCES `bsi_new_model`.`shipment_item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bsi_new_model`.`requirement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bsi_new_model`.`requirement` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bsi_new_model`.`request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bsi_new_model`.`request` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bsi_new_model`.`request_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bsi_new_model`.`request_item` (
  `id` INT NOT NULL,
  `request_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_request_item_request1_idx` (`request_id` ASC),
  CONSTRAINT `fk_request_item_request1`
    FOREIGN KEY (`request_id`)
    REFERENCES `bsi_new_model`.`request` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bsi_new_model`.`quote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bsi_new_model`.`quote` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bsi_new_model`.`quote_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bsi_new_model`.`quote_item` (
  `id` INT NOT NULL,
  `quote_id` INT NOT NULL,
  `order_item_id` INT NOT NULL,
  `order_item_order_id` INT NOT NULL,
  `request_item_id` INT NOT NULL,
  `qty` INT NULL,
  `quote_unit_price` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_quote_item_quote1_idx` (`quote_id` ASC),
  INDEX `fk_quote_item_order_item1_idx` (`order_item_id` ASC, `order_item_order_id` ASC),
  INDEX `fk_quote_item_request_item1_idx` (`request_item_id` ASC),
  CONSTRAINT `fk_quote_item_quote1`
    FOREIGN KEY (`quote_id`)
    REFERENCES `bsi_new_model`.`quote` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_quote_item_order_item1`
    FOREIGN KEY (`order_item_id` , `order_item_order_id`)
    REFERENCES `bsi_new_model`.`order_item` (`id` , `order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_quote_item_request_item1`
    FOREIGN KEY (`request_item_id`)
    REFERENCES `bsi_new_model`.`request_item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bsi_new_model`.`quote_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bsi_new_model`.`quote_role` (
  `id` INT NOT NULL,
  `quote_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_quote_role_quote1_idx` (`quote_id` ASC),
  CONSTRAINT `fk_quote_role_quote1`
    FOREIGN KEY (`quote_id`)
    REFERENCES `bsi_new_model`.`quote` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bsi_new_model`.`requirement_has_request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bsi_new_model`.`requirement_has_request` (
  `requirement_id` INT NOT NULL,
  `request_id` INT NOT NULL,
  PRIMARY KEY (`requirement_id`, `request_id`),
  INDEX `fk_requirement_has_request_request1_idx` (`request_id` ASC),
  INDEX `fk_requirement_has_request_requirement1_idx` (`requirement_id` ASC),
  CONSTRAINT `fk_requirement_has_request_requirement1`
    FOREIGN KEY (`requirement_id`)
    REFERENCES `bsi_new_model`.`requirement` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_requirement_has_request_request1`
    FOREIGN KEY (`request_id`)
    REFERENCES `bsi_new_model`.`request` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bsi_new_model`.`requirement_has_request_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bsi_new_model`.`requirement_has_request_item` (
  `requirement_id` INT NOT NULL,
  `request_item_id` INT NOT NULL,
  PRIMARY KEY (`requirement_id`, `request_item_id`),
  INDEX `fk_requirement_has_request_item_request_item1_idx` (`request_item_id` ASC),
  INDEX `fk_requirement_has_request_item_requirement1_idx` (`requirement_id` ASC),
  CONSTRAINT `fk_requirement_has_request_item_requirement1`
    FOREIGN KEY (`requirement_id`)
    REFERENCES `bsi_new_model`.`requirement` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_requirement_has_request_item_request_item1`
    FOREIGN KEY (`request_item_id`)
    REFERENCES `bsi_new_model`.`request_item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bsi_new_model`.`request_has_party`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bsi_new_model`.`request_has_party` (
  `request_id` INT NOT NULL,
  `party_id` INT NOT NULL,
  PRIMARY KEY (`request_id`, `party_id`),
  INDEX `fk_request_has_party_party1_idx` (`party_id` ASC),
  INDEX `fk_request_has_party_request1_idx` (`request_id` ASC),
  CONSTRAINT `fk_request_has_party_request1`
    FOREIGN KEY (`request_id`)
    REFERENCES `bsi_new_model`.`request` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_request_has_party_party1`
    FOREIGN KEY (`party_id`)
    REFERENCES `bsi_new_model`.`party` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bsi_new_model`.`order_item_has_shipment_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bsi_new_model`.`order_item_has_shipment_item` (
  `order_item_id` INT NOT NULL,
  `order_item_order_id` INT NOT NULL,
  `shipment_item_id` INT NOT NULL,
  `inventory_type_id` INT NOT NULL,
  PRIMARY KEY (`order_item_id`, `order_item_order_id`, `shipment_item_id`),
  INDEX `fk_order_item_has_shipment_item_shipment_item1_idx` (`shipment_item_id` ASC),
  INDEX `fk_order_item_has_shipment_item_order_item1_idx` (`order_item_id` ASC, `order_item_order_id` ASC),
  INDEX `fk_order_item_has_shipment_item_inventory_type1_idx` (`inventory_type_id` ASC),
  CONSTRAINT `fk_order_item_has_shipment_item_order_item1`
    FOREIGN KEY (`order_item_id` , `order_item_order_id`)
    REFERENCES `bsi_new_model`.`order_item` (`id` , `order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_item_has_shipment_item_shipment_item1`
    FOREIGN KEY (`shipment_item_id`)
    REFERENCES `bsi_new_model`.`shipment_item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_item_has_shipment_item_inventory_type1`
    FOREIGN KEY (`inventory_type_id`)
    REFERENCES `bsi_new_model`.`inventory_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bsi_new_model`.`order_item_has_goods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bsi_new_model`.`order_item_has_goods` (
  `order_item_id` INT NOT NULL,
  `order_item_order_id` INT NOT NULL,
  `goods_id` INT NOT NULL,
  PRIMARY KEY (`order_item_id`, `order_item_order_id`, `goods_id`),
  INDEX `fk_order_item_has_goods_goods1_idx` (`goods_id` ASC),
  INDEX `fk_order_item_has_goods_order_item1_idx` (`order_item_id` ASC, `order_item_order_id` ASC),
  CONSTRAINT `fk_order_item_has_goods_order_item1`
    FOREIGN KEY (`order_item_id` , `order_item_order_id`)
    REFERENCES `bsi_new_model`.`order_item` (`id` , `order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_item_has_goods_goods1`
    FOREIGN KEY (`goods_id`)
    REFERENCES `bsi_new_model`.`goods` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
